In [33]:
import pandas as pd

annotations_df = pd.read_csv(SCREENED_TXT, header=0, names=["image_name", "label"])

annotations_df['label'].value_counts()

"""
label
Transverse      387
Longitudinal    379
Unknown         183
Name: count, dtype: int64
"""

'\nlabel\nTransverse      387\nLongitudinal    379\nUnknown         183\nName: count, dtype: int64\n'

# TRANSVERSE VS LONGITUDINAL COMPARISON

In [32]:
from collections import defaultdict
from PIL import Image, ImageDraw

In [ ]:
import csv
import os
import traceback
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import ttach as tta
from PIL import Image
from skimage.measure import label as sklabel
from skimage.measure import regionprops
from skimage.transform import resize
import segmentation_models_pytorch_4TorchLessThan120 as smp


# LOAD DATA CONFIGS 

PROJECT_ROOT = Path(
    "/Users/JanayeCheong/Documents/radiomics_segmentation_models/"
    "TNSCUI2020-Seg-Rank1st"
)

IMG_DIR = PROJECT_ROOT / "train_thyroidXL" / "raw_images"
MASK_DIR = PROJECT_ROOT / "train_thyroidXL" / "masks"

WEIGHT_C1 = (
    PROJECT_ROOT
    / "weigh_and_id"
    / "TNSCUI"
    / "fold1_stage1_trained_on_size_256.pkl"
)

WEIGHT_C2 = (
    PROJECT_ROOT
    / "weigh_and_id"
    / "TNSCUI"
    / "fold1_stage2_trained_on_size_512.pkl"
)

OUTPUT_DIR = PROJECT_ROOT / "inference_outputs_long_vs_trans_v1_07"
PREDICTION_DIR = OUTPUT_DIR / "predicted_masks"
OVERLAY_DIR = OUTPUT_DIR / "overlays"
METRICS_CSV = OUTPUT_DIR / "metrics.csv"

C1_SIZE = 256
C2_SIZE = 512

C1_TTA = True
C2_TTA = True
USE_C2 = True

ORIMG = False
C1_THRESHOLD = 0.5
C2_THRESHOLD = 0.5
C2_RESIZE_ORDER = 0

SAVE_OVERLAYS = True
CONTINUE_ON_ERROR = True

SUPPORTED_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".tif",
    ".tiff",
}

In [67]:
SCREENED_TXT = Path(
    "TNSCUI2020-Seg-Rank1st/train_thyroidXL/screened.txt"
)

PATIENT_COMPARISON_DIR = OUTPUT_DIR / "patient_view_comparisons"
PATIENT_METRICS_CSV = OUTPUT_DIR / "patient_view_metrics.csv"

In [68]:
def load_view_annotations(annotation_path: Path) -> Dict[str, str]:
    """
    Read screened.txt annotations.

    Expected format:
    # 8 digits + underscore + 8 digits + underscore + 1 digit
    
    first 8 digits indicate the patient ID

        ,classification
        00003307_17EE0585_0,Transverse 
        00003723_CCF3845C_2,Longitudinal
        ...

    Returns
    -------
    {
        "00003307_17EE0585_0": "Transverse",
        "00003723_CCF3845C_2": "Longitudinal",
        ...
    }
    """
    if not annotation_path.exists():
        raise FileNotFoundError(
            f"View annotation file not found: {annotation_path}"
        )

    annotations: Dict[str, str] = {}

    with annotation_path.open(
        "r",
        newline="",
        encoding="utf-8-sig",
    ) as f:

        reader = csv.reader(f)

        for row in reader:

            # Skip completely blank rows
            if not row:
                continue

            # Some files may contain blank lines
            if len(row) < 2:
                continue

            image_id = row[0].strip()
            classification = row[1].strip()

            # Skip header:
            # ,classification
            if (
                not image_id
                and classification.lower() == "classification"
            ):
                continue

            if not image_id:
                continue

            if not classification:
                classification = "Unknown"

            annotations[image_id.lower()] = classification

    print(
        f"Loaded view annotations for "
        f"{len(annotations)} images."
    )

    return annotations

In [ ]:
def load_screened_patients(
    screened_path: Path,
) -> Dict[str, List[Dict]]:
    """
    Read screened image annotations and group by patient ID.

    # EXAMPLE of file format for loading screened patients: 00003307_17EE0585_0,Transverse

    Patient ID is defined as the first 8 characters.
    """

    if not screened_path.exists():
        raise FileNotFoundError(
            f"Screened annotation file not found: {screened_path}"
        )

    patients = defaultdict(list)

    with screened_path.open(
        "r",
        newline="",
        encoding="utf-8-sig",
    ) as f:

        reader = csv.reader(f)

        for row in reader:

            if not row or len(row) < 2:
                continue

            image_id = row[0].strip()
            view = row[1].strip()

            # Header is:
            # ,classification
            if not image_id:
                continue

            if not view:
                view = "Unknown"

            patient_id = image_id[:8]

            patients[patient_id].append(
                {
                    "image_id": image_id,
                    "view": view,
                }
            )

    return dict(patients)


def build_image_index(
    image_dir: Path,
) -> Dict[str, Path]:

    index: Dict[str, Path] = {}

    for path in discover_images(image_dir):

        key = path.stem.lower()

        if key in index:
            raise ValueError(
                f"Duplicate image stem '{path.stem}' found:\n"
                f"  {index[key]}\n"
                f"  {path}"
            )

        index[key] = path

    return index

In [ ]:
def save_patient_comparison(
    patient_id: str,
    patient_results: List[Dict],
    output_path: Path,
) -> None:
    """
    Save successful overlays for one patient side-by-side.

    Each panel contains:
        - view
        - image ID
        - IoU
        - DSC
    """

    successful = [
        row
        for row in patient_results
        if (
            row["status"] == "ok"
            and row["overlay_path"]
        )
    ]

    # From patient results, if there are less than 2 successful overlays, we cannot create a comparison image. Return
    if len(successful) < 2:
        return

    panels = []

    target_width = 500
    header_height = 85

    # Put Transverse first, then Longitudinal,
    # then Unknown/anything else.
    view_order = {
        "transverse": 0,
        "longitudinal": 1,
        "unknown": 2,
    }

    successful = sorted(
        successful,
        key=lambda row: (
            view_order.get(
                str(row["view"]).lower(),
                99,
            ),
            row["image_id"],
        ),
    )

    for row in successful:

        overlay_path = Path(
            row["overlay_path"]
        )

        if not overlay_path.exists():
            continue

        with Image.open(
            overlay_path
        ) as img:

            overlay = img.convert("RGB")

        scale = (
            target_width
            / overlay.width
        )

        resized_height = int(
            overlay.height * scale
        )

        overlay = overlay.resize(
            (
                target_width,
                resized_height,
            )
        )

        panel = Image.new(
            "RGB",
            (
                target_width,
                resized_height + header_height,
            ),
            "white",
        )

        panel.paste(
            overlay,
            (0, header_height),
        )

        draw = ImageDraw.Draw(panel)

        text = (
            f"{row['view']}\n"
            f"{row['image_id']}\n"
            f"IoU={row['iou']:.4f} | "
            f"DSC={row['dsc']:.4f}"
        )

        draw.multiline_text(
            (10, 8),
            text,
            fill="black",
            spacing=4,
        )

        panels.append(panel)

    if len(panels) < 2:
        return

    title_height = 45

    max_height = max(
        panel.height
        for panel in panels
    )

    total_width = sum(
        panel.width
        for panel in panels
    )

    combined = Image.new(
        "RGB",
        (
            total_width,
            max_height + title_height,
        ),
        "white",
    )

    draw = ImageDraw.Draw(combined)

    draw.text(
        (10, 12),
        f"Patient {patient_id}",
        fill="black",
    )

    x_position = 0

    for panel in panels:

        combined.paste(
            panel,
            (
                x_position,
                title_height,
            ),
        )

        x_position += panel.width

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    combined.save(output_path)

In [71]:
def save_patient_metrics(
    results: List[Dict],
    output_path: Path,
) -> None:

    grouped = defaultdict(list)

    for row in results:

        if row["status"] != "ok":
            continue

        grouped[
            row["patient_id"]
        ].append(row)

    patient_rows = []

    for patient_id, rows in sorted(
        grouped.items()
    ):

        transverse = [
            row
            for row in rows
            if str(
                row["view"]
            ).lower() == "transverse"
        ]

        longitudinal = [
            row
            for row in rows
            if str(
                row["view"]
            ).lower() == "longitudinal"
        ]

        unknown = [
            row
            for row in rows
            if str(row["view"]).lower()
            not in {
                "transverse",
                "longitudinal",
            }
        ]

        def mean_metric(
            selected_rows,
            metric_name,
        ):

            if not selected_rows:
                return ""

            return float(
                np.mean(
                    [
                        row[metric_name]
                        for row
                        in selected_rows
                    ]
                )
            )

        transverse_iou = mean_metric(
            transverse,
            "iou",
        )

        longitudinal_iou = mean_metric(
            longitudinal,
            "iou",
        )

        transverse_dsc = mean_metric(
            transverse,
            "dsc",
        )

        longitudinal_dsc = mean_metric(
            longitudinal,
            "dsc",
        )

        if (
            transverse_iou != ""
            and longitudinal_iou != ""
        ):

            iou_difference = (
                longitudinal_iou
                - transverse_iou
            )

            dsc_difference = (
                longitudinal_dsc
                - transverse_dsc
            )

        else:

            iou_difference = ""
            dsc_difference = ""

        patient_rows.append(
            {
                "patient_id":
                    patient_id,

                "total_images":
                    len(rows),

                "transverse_images":
                    len(transverse),

                "longitudinal_images":
                    len(longitudinal),

                "unknown_images":
                    len(unknown),

                "transverse_mean_iou":
                    transverse_iou,

                "longitudinal_mean_iou":
                    longitudinal_iou,

                "iou_long_minus_trans":
                    iou_difference,

                "transverse_mean_dsc":
                    transverse_dsc,

                "longitudinal_mean_dsc":
                    longitudinal_dsc,

                "dsc_long_minus_trans":
                    dsc_difference,

                "has_both_views":
                    int(
                        len(transverse) > 0
                        and
                        len(longitudinal) > 0
                    ),
            }
        )

    fieldnames = [
        "patient_id",
        "total_images",
        "transverse_images",
        "longitudinal_images",
        "unknown_images",

        "transverse_mean_iou",
        "longitudinal_mean_iou",
        "iou_long_minus_trans",

        "transverse_mean_dsc",
        "longitudinal_mean_dsc",
        "dsc_long_minus_trans",

        "has_both_views",
    ]

    with output_path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as f:

        writer = csv.DictWriter(
            f,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(
            patient_rows
        )

In [72]:
annotations_df

              image_name         label
0    00003307_17EE0585_0    Transverse
1    00003723_CCF3845C_2  Longitudinal
2    00001962_034B467C_1    Transverse
3    00002300_E60B804B_0    Transverse
4    00003387_76B10567_2    Transverse
..                   ...           ...
944  00000578_AAD6BA89_1       Unknown
945  00001334_CEB80814_1    Transverse
946  00003110_ABBD7CBC_0       Unknown
947  00001342_FFEB8295_0       Unknown
948  00002464_2C37C1B5_0    Transverse

[949 rows x 2 columns]

In [ ]:
from collections import defaultdict, Counter
from pathlib import Path

IMG_DIR = PROJECT_ROOT / "train_thyroidXL" / "raw_images"

# Find images recursively and allow common extensions
image_files = [
    p for p in IMG_DIR.rglob("*")
    if p.is_file()
    and p.suffix.lower() in {".png", ".jpg", ".jpeg"}
]

print(f"Total image files found: {len(image_files)}")

# ------------------------------------------------------------
# Group by FIRST 8 CHARACTERS of filename stem
# ------------------------------------------------------------

patients = defaultdict(list)

for image_path in image_files:
    stem = image_path.stem.strip()

    patient_id = stem[:8]

    patients[patient_id].append(image_path)



# Show all patients with MORE THAN ONE image


repeated_patients = {
    patient_id: paths
    for patient_id, paths in patients.items()
    if len(paths) > 1
}

print(f"Unique patients: {len(patients)}")
print(
    f"Patients with >1 image: "
    f"{len(repeated_patients)}"
)

print("\n" + "=" * 70)
print("PATIENTS WITH MULTIPLE IMAGES")
print("=" * 70)

for patient_id, paths in sorted(
    repeated_patients.items(),
    key=lambda x: len(x[1]),
    reverse=True,
):

    print(
        f"\n{patient_id}: "
        f"{len(paths)} images"
    )

    for path in sorted(paths):
        print(f"    {path.name}")

Total image files found: 9541
Unique patients: 3354
Patients with >1 image: 3180

======================================================================
PATIENTS WITH MULTIPLE IMAGES
======================================================================

00004012: 10 images
    00004012_08B25F9C_9.png
    00004012_54792304_4.png
    00004012_60F3C0C2_1.png
    00004012_6E510AB4_8.png
    00004012_91D440E8_3.png
    00004012_AD725ABC_0.png
    00004012_BD239B56_7.png
    00004012_E1AFF0ED_2.png
    00004012_EBF1AAD9_5.png
    00004012_EC553CF6_6.png

00003730: 8 images
    00003730_13600386_2.png
    00003730_2D63A125_0.png
    00003730_429CBA29_5.png
    00003730_489C1FC9_3.png
    00003730_5A34EAFF_1.png
    00003730_5DA17244_3.png
    00003730_AD047E8B_4.png
    00003730_E247AD47_2.png

00003950: 8 images
    00003950_1B7C16DE_2.png
    00003950_2B4C084A_5.png
    00003950_2BE0C739_0.png
    00003950_330114F4_4.png
    00003950_50985A09_3.png
    00003950_953153A7_7.png
    00003950_A752ADE8_1.png
    00003950_CB339AA2_6.png

00004065: 8 images
    00004065_1B7A9C45_8.png
    00004065_77CA138D_7.png
    00004065_78063259_12.png
    00004065_78063259_5.png
    00004065_816FEE7E_6.png
    00004065_824BD5A8_3.png
    00004065_E2CE781A_4.png
    00004065_F0BE6294_9.png

00004066: 8 images
    00004066_27ED9D6D_0.png
    00004066_27ED9D6D_4.png
    00004066_2A6189C5_1.png
    00004066_2A6189C5_5.png
    00004066_3EB0B9C9_2.png
    00004066_3EB0B9C9_6.png
    00004066_6DACC452_3.png
    00004066_6DACC452_7.png

00002564: 7 images
    00002564_074B4873_2.png
    00002564_091C8F17_1.png
    00002564_2CB5B019_1.png
    00002564_3DBCDBAF_0.png
    00002564_48C9A5B9_3.png
    00002564_68DC4A98_2.png
    00002564_C32EFEC0_0.png

00003381: 7 images
    00003381_38575B2C_0.png
    00003381_4F4158C1_2.png
    00003381_640A19F5_1.png
    00003381_9A2935B1_3.png
    00003381_AF78312F_1.png
    00003381_B2A8FE23_0.png
    00003381_E64F742D_2.png

00000196: 7 images
    00000196_1E672E9F_2.png
    00000196_541450D3_1.png
    00000196_5C7283E3_0.png
    00000196_7EC57B51_6.png
    00000196_94A0DC10_5.png
    00000196_AD5AD212_3.png
    00000196_E68FE536_4.png

00003122: 7 images
    00003122_00C3A62C_6.png
    00003122_7D7EE2CA_2.png
    00003122_7FE05686_3.png
    00003122_86351FA7_5.png
    00003122_B1E61393_1.png
    00003122_BFEAE01A_4.png
    00003122_C0C332B4_7.png

00004078: 7 images
    00004078_08463DE2_5.png
    00004078_327DCC56_6.png
    00004078_ACCA614B_8.png
    00004078_AF179F9D_3.png
    00004078_C694F551_4.png
    00004078_F1C94F36_9.png
    00004078_FC89B15B_7.png

00002733: 7 images
    00002733_1F23CD76_5.png
    00002733_4B08AF5D_6.png
    00002733_6A8B8518_4.png
    00002733_A7A93E1E_2.png
    00002733_B7F3BFDC_1.png
    00002733_EC09419F_3.png
    00002733_F4E2024A_0.png

00003712: 6 images
    00003712_3B60994C_4.png
    00003712_49F762EF_1.png
    00003712_755843D3_2.png
    00003712_86F03B80_0.png
    00003712_9A91F644_3.png
    00003712_DAB6E827_5.png

00001225: 6 images
    00001225_05DDD6A2_2.png
    00001225_6376CF50_0.png
    00001225_9226EB85_1.png
    00001225_B6BE32AB_3.png
    00001225_D48551F4_5.png
    00001225_EF55F128_4.png

00003110: 6 images
    00003110_15944615_1.png
    00003110_170514ED_2.png
    00003110_1F409AF0_4.png
    00003110_ABBD7CBC_0.png
    00003110_C7680521_3.png
    00003110_E741AC77_5.png

00004081: 6 images
    00004081_04BAE3ED_8.png
    00004081_19DD08D0_5.png
    00004081_699CAEB7_7.png
    00004081_6D964F9E_1.png
    00004081_6D964F9E_6.png
    00004081_E69F1D58_9.png

00002615: 6 images
    00002615_0A4B3554_1.png
    00002615_402AED56_2.png
    00002615_7ABAF7BD_0.png
    00002615_A68A48CE_3.png
    00002615_DC4EC5C7_4.png
    00002615_F0E4925D_5.png

00000441: 6 images
    00000441_4BF40F07_1.png
    00000441_5C6613FD_3.png
    00000441_9349AC2C_0.png
    00000441_9A6CB7CC_0.png
    00000441_C0FAA0E4_1.png
    00000441_D9847AD5_2.png

00000450: 6 images
    00000450_13816249_0.png
    00000450_1536E6C9_2.png
    00000450_9520A5DD_3.png
    00000450_A70E1077_5.png
    00000450_BA12FD9E_1.png
    00000450_CD3C7173_4.png

00004068: 6 images
    00004068_2290D21E_1.png
    00004068_2290D21E_4.png
    00004068_4562DFC9_2.png
    00004068_4562DFC9_5.png
    00004068_9508DCAF_0.png
    00004068_9508DCAF_3.png

00000262: 6 images
    00000262_23CA9266_2.png
    00000262_25ABADCD_4.png
    00000262_4574FD78_0.png
    00000262_81C6F4E1_5.png
    00000262_869805ED_1.png
    00000262_8E7B7F9C_3.png

00002721: 6 images
    00002721_2D5874CF_4.png
    00002721_7C34CB64_1.png
    00002721_ABEDF137_3.png
    00002721_B8594E0F_2.png
    00002721_CF0E98B9_0.png
    00002721_FFCC49C5_5.png

00002468: 6 images
    00002468_43E6E951_2.png
    00002468_54506680_3.png
    00002468_5A24D58B_1.png
    00002468_7378AB98_0.png
    00002468_DF28C509_1.png
    00002468_F37B1F9A_2.png

00003640: 6 images
    00003640_29340133_3.png
    00003640_5CF62128_2.png
    00003640_6F811053_4.png
    00003640_7D65B26E_1.png
    00003640_CC3736FD_5.png
    00003640_F72BF997_0.png

00002559: 6 images
    00002559_71248D44_2.png
    00002559_79779E5E_0.png
    00002559_92615B40_1.png
    00002559_B14C7747_3.png
    00002559_F0A7EFDE_4.png
    00002559_F591D93C_5.png

00001184: 6 images
    00001184_2528E413_1.png
    00001184_450166FE_0.png
    00001184_6FA751DD_1.png
    00001184_7AB39EFC_2.png
    00001184_D8B78BD5_2.png
    00001184_EAA10B2F_0.png

00000241: 6 images
    00000241_083DE2AF_1.png
    00000241_5CAC439A_2.png
    00000241_7777E66E_4.png
    00000241_93EC0746_0.png
    00000241_98B5EE57_5.png
    00000241_ED037116_3.png

00000684: 6 images
    00000684_13FD06E1_2.png
    00000684_726B8EE1_0.png
    00000684_7FD62FA3_5.png
    00000684_9821BB33_1.png
    00000684_AE4B947E_4.png
    00000684_F539D932_3.png

00003780: 6 images
    00003780_108AC2B6_1.png
    00003780_12EA8347_3.png
    00003780_8275C69E_4.png
    00003780_B0DB9BB6_5.png
    00003780_BA8B5FCC_2.png
    00003780_C16C6A14_0.png

00002196: 6 images
    00002196_2DC3C4E3_2.png
    00002196_382813DE_1.png
    00002196_9F19D9DA_0.png
    00002196_ADE93917_1.png
    00002196_E5556572_0.png
    00002196_FB774545_2.png

00002784: 6 images
    00002784_1B2FC9D2_0.png
    00002784_21A99F99_3.png
    00002784_B885B907_2.png
    00002784_D8A03C35_4.png
    00002784_E6B0F528_5.png
    00002784_F21854AE_1.png

00004067: 6 images
    00004067_0672EDAE_1.png
    00004067_0672EDAE_4.png
    00004067_A86E78E1_2.png
    00004067_A86E78E1_5.png
    00004067_EF075678_0.png
    00004067_EF075678_3.png

00002722: 5 images
    00002722_062E9BD2_4.png
    00002722_0B32645F_1.png
    00002722_0B61FD23_2.png
    00002722_138E3BB1_0.png
    00002722_43E1743A_3.png

00003891: 5 images
    00003891_1D15B034_0.png
    00003891_51BAF52F_1.png
    00003891_9CA771DD_2.png
    00003891_D0FA9BC4_3.png
    00003891_D1D14835_4.png

00003118: 5 images
    00003118_01BA5E39_4.png
    00003118_0E3C3EAF_0.png
    00003118_109FF640_3.png
    00003118_341975A4_1.png
    00003118_3B8CCF61_2.png

00000712: 5 images
    00000712_5E523D40_4.png
    00000712_7E2C8D0E_1.png
    00000712_95D202A1_2.png
    00000712_D8D5976D_3.png
    00000712_F5B42CFA_0.png

00002980: 5 images
    00002980_1B9B2283_0.png
    00002980_5A1D52F5_3.png
    00002980_817C071B_2.png
    00002980_868B601B_4.png
    00002980_AD50AF95_1.png

00000460: 5 images
    00000460_09D63FFE_3.png
    00000460_B4E7FA1A_1.png
    00000460_C8B2D1A0_4.png
    00000460_D5D5D7BB_2.png
    00000460_DBD30636_0.png

00003772: 5 images
    00003772_3C33EC01_4.png
    00003772_7FC5049C_0.png
    00003772_9AC29707_3.png
    00003772_CA14876A_2.png
    00003772_E7B70A6B_1.png

00003428: 5 images
    00003428_05CEF222_0.png
    00003428_1D4D9575_4.png
    00003428_6B106764_2.png
    00003428_C744B01F_1.png
    00003428_F6C07225_3.png

00004058: 5 images
    00004058_01CCEBC6_9.png
    00004058_324C24DC_5.png
    00004058_6172C737_6.png
    00004058_86EEB183_7.png
    00004058_9E6C4CFD_8.png

00003567: 5 images
    00003567_1BC6762E_3.png
    00003567_1C800DF9_0.png
    00003567_508FEF53_1.png
    00003567_B35E659B_4.png
    00003567_BDF68556_2.png

00003036: 5 images
    00003036_08686C62_1.png
    00003036_19FA48B5_4.png
    00003036_22FC7644_2.png
    00003036_CC154263_3.png
    00003036_EA94EA4C_0.png

00003037: 5 images
    00003037_03F931F6_0.png
    00003037_084EB684_4.png
    00003037_2E397FF8_2.png
    00003037_79B21075_1.png
    00003037_AA3346CF_3.png

00004056: 5 images
    00004056_0792F6DC_7.png
    00004056_612999E3_8.png
    00004056_7305A756_9.png
    00004056_9504FC8A_5.png
    00004056_E129D4B4_6.png

00003358: 5 images
    00003358_25C7AADC_2.png
    00003358_8798CE91_1.png
    00003358_C0F747E8_4.png
    00003358_CFAE80F2_0.png
    00003358_EED38051_3.png

00003734: 5 images
    00003734_095CF484_2.png
    00003734_833FDD6F_4.png
    00003734_AF2ECC70_1.png
    00003734_B138FBCE_0.png
    00003734_C3FBDF74_3.png

00004771: 5 images
    00004771_13936F80_3.png
    00004771_66316A2D_0.png
    00004771_A4FAFF73_2.png
    00004771_B4A0E9AB_4.png
    00004771_ED225E6A_1.png

00003986: 5 images
    00003986_2262F9EA_2.png
    00003986_2D3D9910_1.png
    00003986_42FEAEF2_0.png
    00003986_5051110D_4.png
    00003986_95E22D59_3.png

00002977: 5 images
    00002977_350A2555_3.png
    00002977_6B716B79_4.png
    00002977_81CAFE5C_0.png
    00002977_827E7EBE_1.png
    00002977_8BBE73FC_2.png

00003114: 5 images
    00003114_60445BD8_4.png
    00003114_659A2303_2.png
    00003114_8AC5A8D5_3.png
    00003114_B5DAAD5E_1.png
    00003114_F5592EA2_0.png

00002526: 5 images
    00002526_2F0D8855_4.png
    00002526_5A17A25B_0.png
    00002526_AAF6FE7A_1.png
    00002526_DF0198E1_3.png
    00002526_FDEADDA0_2.png

00003853: 5 images
    00003853_399D6C00_4.png
    00003853_4BD6C465_1.png
    00003853_92334B5A_3.png
    00003853_9DFF464B_0.png
    00003853_B6712CEF_2.png

00003259: 5 images
    00003259_3F48AD1A_3.png
    00003259_60EB02A6_1.png
    00003259_A120ADFD_2.png
    00003259_A15A27FF_4.png
    00003259_F9BF3AA1_0.png

00002926: 5 images
    00002926_0EBB841A_4.png
    00002926_166FBDD7_1.png
    00002926_4871FFDB_2.png
    00002926_6DD544CC_3.png
    00002926_E4AB0B20_0.png

00003586: 5 images
    00003586_2639D573_3.png
    00003586_26F2435B_4.png
    00003586_6654DCAB_2.png
    00003586_E8976C5A_1.png
    00003586_FD2B1DF8_0.png

00002799: 5 images
    00002799_539B270C_1.png
    00002799_6D320A6C_2.png
    00002799_ABE59D7E_4.png
    00002799_B228CD5D_3.png
    00002799_F543E071_0.png

00002890: 5 images
    00002890_15BC3AD5_0.png
    00002890_43D74DD7_3.png
    00002890_9CE55C0E_2.png
    00002890_9D1351FA_4.png
    00002890_D87E708A_1.png

00000518: 5 images
    00000518_653C16B4_1.png
    00000518_6788FA69_0.png
    00000518_A435D57B_3.png
    00000518_A750768D_4.png
    00000518_FA383718_2.png

00004643: 5 images
    00004643_223F3869_1.png
    00004643_76DDF6D6_2.png
    00004643_A2F12318_0.png
    00004643_AE1C4CAC_4.png
    00004643_EFD26A10_3.png

00000272: 5 images
    00000272_01B4FBDA_1.png
    00000272_1E53FB13_0.png
    00000272_4889A289_2.png
    00000272_7A4F35B8_3.png
    00000272_AE3A1572_4.png

00002332: 5 images
    00002332_46F9EB52_1.png
    00002332_88B1C73A_3.png
    00002332_A44B166A_4.png
    00002332_C0887F4D_2.png
    00002332_FB6516E9_0.png

00002800: 5 images
    00002800_065A6BB9_3.png
    00002800_15C58669_4.png
    00002800_3CE6F847_1.png
    00002800_D0460397_2.png
    00002800_F3CE5795_0.png

00003856: 5 images
    00003856_02131EA5_0.png
    00003856_106464E8_3.png
    00003856_3758331C_4.png
    00003856_4EF6F99E_2.png
    00003856_AFCDFFFA_1.png

00004575: 5 images
    00004575_0418709F_4.png
    00004575_36A0B468_0.png
    00004575_7EAC7105_3.png
    00004575_E9A015D8_1.png
    00004575_F8AB8366_2.png

00003593: 5 images
    00003593_50FE5504_4.png
    00003593_833876BE_3.png
    00003593_83EF0D05_0.png
    00003593_D41F4309_5.png
    00003593_F2F2CFE4_1.png

00003619: 5 images
    00003619_1F5B87E0_4.png
    00003619_7DB150B1_2.png
    00003619_D4846D8B_3.png
    00003619_E9C01D41_1.png
    00003619_EC35A068_0.png

00002763: 5 images
    00002763_1E826738_0.png
    00002763_2E1DA5C5_1.png
    00002763_613EF827_3.png
    00002763_7EC11016_4.png
    00002763_F7DC6320_2.png

00004652: 5 images
    00004652_0427C106_4.png
    00004652_0A29B680_0.png
    00004652_76BCAFE1_2.png
    00004652_8530F4F4_1.png
    00004652_B19D5F9B_3.png

00003776: 5 images
    00003776_6E4A8495_0.png
    00003776_730D9287_4.png
    00003776_84454671_1.png
    00003776_98D234E6_2.png
    00003776_CC209DC2_3.png

00003325: 5 images
    00003325_7BAA589B_1.png
    00003325_8E1954EB_2.png
    00003325_A2F81EB3_0.png
    00003325_CE184FAE_4.png
    00003325_EC579A88_3.png

00002895: 5 images
    00002895_429864E1_0.png
    00002895_7C49733F_2.png
    00002895_CC264AF4_4.png
    00002895_E458BC94_1.png
    00002895_FAFD7172_3.png

00003501: 5 images
    00003501_30320647_1.png
    00003501_30AEE784_0.png
    00003501_3411CC0F_4.png
    00003501_4111EA1C_3.png
    00003501_905D0A20_2.png

00003006: 5 images
    00003006_44EDC1C2_0.png
    00003006_67F960D5_4.png
    00003006_786AC759_3.png
    00003006_C0A116B3_1.png
    00003006_D7CBADCF_2.png

00002996: 5 images
    00002996_386553E3_1.png
    00002996_8D148A22_4.png
    00002996_B5872E41_3.png
    00002996_D2F7979B_0.png
    00002996_E0ACB214_2.png

00002923: 5 images
    00002923_34DC7157_3.png
    00002923_7FFE9FDD_1.png
    00002923_9B3EA2C1_2.png
    00002923_9F6448EE_4.png
    00002923_C87E4B6E_0.png

00002990: 5 images
    00002990_48D60585_1.png
    00002990_5063736D_0.png
    00002990_5F51C9F6_4.png
    00002990_7B0C9B68_2.png
    00002990_87FE3D4D_3.png

00003571: 5 images
    00003571_109E8818_4.png
    00003571_1917E111_3.png
    00003571_3E526B04_0.png
    00003571_5DAE5993_2.png
    00003571_A08DD8C8_1.png

00000187: 5 images
    00000187_0EDD5F19_2.png
    00000187_3F6254BA_1.png
    00000187_72DFBD14_0.png
    00000187_B7BAEC3B_3.png
    00000187_FFE5A03F_4.png

00003693: 5 images
    00003693_236458EA_2.png
    00003693_67C00DE2_4.png
    00003693_86836D96_3.png
    00003693_E030DE9E_0.png
    00003693_FBB6D4E8_1.png

00003005: 5 images
    00003005_18EACD54_1.png
    00003005_3C0D3466_4.png
    00003005_80E8D8AC_3.png
    00003005_C8BA172C_0.png
    00003005_FCF27DE7_2.png

00003637: 5 images
    00003637_2D6203F7_3.png
    00003637_7ACBFA2F_0.png
    00003637_9D8BCD34_4.png
    00003637_A1D36A9C_2.png
    00003637_DB6E2D3C_1.png

00003594: 5 images
    00003594_2A444DEC_3.png
    00003594_36704F9E_4.png
    00003594_483849DA_2.png
    00003594_C78A8462_1.png
    00003594_EBEE30FE_0.png

00003791: 5 images
    00003791_19E42A32_1.png
    00003791_4B0338E6_2.png
    00003791_9CC36F31_3.png
    00003791_AE22E112_0.png
    00003791_ECA5E3DC_4.png

00002851: 5 images
    00002851_1952A13A_4.png
    00002851_420A4961_2.png
    00002851_424024E6_0.png
    00002851_7680B2B8_3.png
    00002851_97E8CC2A_1.png

00003836: 5 images
    00003836_0C6DE9FE_2.png
    00003836_54C2C708_0.png
    00003836_88CBF0CF_1.png
    00003836_8E452E0D_3.png
    00003836_D5220E52_4.png

00002360: 5 images
    00002360_073E1148_4.png
    00002360_25815110_1.png
    00002360_35EFDD8D_3.png
    00002360_C6C49C10_0.png
    00002360_E9A8DE1E_2.png

00003412: 5 images
    00003412_3386C4BE_3.png
    00003412_5D9F7193_0.png
    00003412_69AFBB57_4.png
    00003412_8A2DC378_2.png
    00003412_BF7FA97B_1.png

00004079: 5 images
    00004079_0F3CD0E6_7.png
    00004079_736F7B7A_6.png
    00004079_B3DCF89C_5.png
    00004079_FEBE3104_0.png
    00004079_FEBE3104_4.png

00003512: 5 images
    00003512_0FA49531_0.png
    00003512_1146B0BB_3.png
    00003512_2705238D_2.png
    00003512_6EF314CC_4.png
    00003512_C6C38179_1.png

00003029: 5 images
    00003029_04BAA311_2.png
    00003029_0ACAA4EF_1.png
    00003029_99EE2207_4.png
    00003029_9DA13221_3.png
    00003029_C94311B8_0.png

00002809: 5 images
    00002809_2B244BD1_4.png
    00002809_4A884EE6_2.png
    00002809_775B9D0E_3.png
    00002809_8CF11532_0.png
    00002809_D5780D34_1.png

00003414: 5 images
    00003414_28C2D590_0.png
    00003414_A046EFEA_4.png
    00003414_AD3381BB_3.png
    00003414_C212C80D_2.png
    00003414_C931728B_1.png

00004672: 5 images
    00004672_2A72B04B_4.png
    00004672_4E8529B5_2.png
    00004672_560D631C_0.png
    00004672_74F94270_1.png
    00004672_8D5D601B_3.png

00002907: 5 images
    00002907_21123CF6_2.png
    00002907_58BD7BB7_3.png
    00002907_9030B3CA_4.png
    00002907_AFEB80B3_1.png
    00002907_C1BD01C5_0.png

00003021: 5 images
    00003021_5939B52A_0.png
    00003021_B75F2D87_4.png
    00003021_C3E3EC5D_2.png
    00003021_DEFD37A7_1.png
    00003021_EAD77B6F_3.png

00003063: 5 images
    00003063_002913B4_3.png
    00003063_5BFA642A_0.png
    00003063_8DF5AC6B_1.png
    00003063_991910CF_4.png
    00003063_EE0E1451_2.png

00003198: 5 images
    00003198_0FB40F4D_2.png
    00003198_2A30DCA6_1.png
    00003198_327CAA8B_0.png
    00003198_E56713A3_4.png
    00003198_FBB0D65F_3.png

00003318: 5 images
    00003318_7869C5CD_1.png
    00003318_AE8D3045_2.png
    00003318_B893CF46_0.png
    00003318_D4338447_4.png
    00003318_FB691023_3.png

00000247: 5 images
    00000247_0133284A_4.png
    00000247_27B1C4F8_0.png
    00000247_8E62210A_2.png
    00000247_9FE051F8_1.png
    00000247_E3406AB9_3.png

00002661: 5 images
    00002661_0AD2D58A_3.png
    00002661_23CCE7AF_4.png
    00002661_5EBFCD83_2.png
    00002661_BFF4AAD4_0.png
    00002661_D2129279_1.png

00002627: 5 images
    00002627_08325BF7_1.png
    00002627_4DB6AC62_0.png
    00002627_4E034C65_4.png
    00002627_E13AE616_2.png
    00002627_FEB68BFE_3.png

00000511: 5 images
    00000511_14789D57_1.png
    00000511_1543A41B_4.png
    00000511_6FD2E6A4_2.png
    00000511_AAB4C862_3.png
    00000511_B2D5AEDE_0.png

00000321: 5 images
    00000321_30380E08_1.png
    00000321_3DF2ED4F_2.png
    00000321_4BB7974C_3.png
    00000321_C9723D66_0.png
    00000321_F46827AB_4.png

00003687: 5 images
    00003687_1F3BAD8F_0.png
    00003687_2AEA632E_3.png
    00003687_5E2BD845_2.png
    00003687_85E370F7_1.png
    00003687_8E3C991E_4.png

00000591: 5 images
    00000591_1FB0848C_2.png
    00000591_260E8E6D_0.png
    00000591_64453B4F_3.png
    00000591_B375277F_4.png
    00000591_E93BD764_1.png

00003694: 5 images
    00003694_27455341_4.png
    00003694_5A81BA0C_0.png
    00003694_6CE90B98_3.png
    00003694_B486F0E8_2.png
    00003694_EF8BAD39_1.png

00004603: 5 images
    00004603_0BA7C709_4.png
    00004603_378A2804_1.png
    00004603_D18A5C49_2.png
    00004603_EDAAA1B5_3.png
    00004603_F0505CB4_0.png

00001107: 5 images
    00001107_0C6824A9_0.png
    00001107_25DBE620_1.png
    00001107_5AFD4535_2.png
    00001107_CA8E5F47_0.png
    00001107_D040D18B_1.png

00002371: 5 images
    00002371_0D92E4FE_2.png
    00002371_B6E9136A_0.png
    00002371_BC367B9A_4.png
    00002371_F492BF4D_1.png
    00002371_FF5F868E_3.png

00002772: 5 images
    00002772_3320E1A3_0.png
    00002772_ACB279F4_4.png
    00002772_B250C6B8_2.png
    00002772_CFABB0C2_3.png
    00002772_DB75D619_1.png

00003575: 5 images
    00003575_81ED5014_1.png
    00003575_8A89E5AE_3.png
    00003575_B2D92720_0.png
    00003575_CC3DEE17_2.png
    00003575_EAB877BC_4.png

00003124: 5 images
    00003124_103EA84E_0.png
    00003124_2AA25185_2.png
    00003124_A375F88C_4.png
    00003124_D14339FD_1.png
    00003124_DD3C730B_3.png

00003802: 5 images
    00003802_262647DB_2.png
    00003802_6CBE9344_1.png
    00003802_7EFED5CD_4.png
    00003802_938DFD26_3.png
    00003802_FD980408_0.png

00002608: 5 images
    00002608_11CAD570_4.png
    00002608_23272331_1.png
    00002608_3DA720B8_2.png
    00002608_7D274ECF_0.png
    00002608_9817C5DC_3.png

00002912: 5 images
    00002912_1592F468_1.png
    00002912_43B5D7DC_3.png
    00002912_897EA1F8_2.png
    00002912_AEC61867_4.png

In [ ]:
from collections import defaultdict, Counter
from pathlib import Path
import csv


SCREENED_TXT = PROJECT_ROOT / "train_thyroidXL" / "screened_annotations.txt"


# Group screened images by first 8 characters = patient ID


patients = defaultdict(list)

with SCREENED_TXT.open(
    "r",
    newline="",
    encoding="utf-8-sig",
) as f:

    reader = csv.reader(f)

    for row in reader:

        if not row or len(row) < 2:
            continue

        image_id = row[0].strip()
        view = row[1].strip()

        # Skip header: ,classification
        if not image_id:
            continue

        patient_id = image_id[:8]

        patients[patient_id].append(
            {
                "image_id": image_id,
                "view": view,
            }
        )


# ------------------------------------------------------------
# Keep only repeat patients
# ------------------------------------------------------------

repeat_patients = {
    patient_id: images
    for patient_id, images in patients.items()
    if len(images) > 1
}


print(f"Total unique patients in screened file: {len(patients)}")
print(
    f"Repeat patients in screened file: "
    f"{len(repeat_patients)}"
)



# Print each repeat patient and their images/views


print("\n" + "=" * 70)
print("REPEAT PATIENTS")
print("=" * 70)

for patient_id, images in sorted(
    repeat_patients.items(),
    key=lambda x: len(x[1]),
    reverse=True,
):

    print(
        f"\n{patient_id}: "
        f"{len(images)} screened images"
    )

    for item in images:
        print(
            f"    {item['image_id']} "
            f"| {item['view']}"
        )

Total unique patients in screened file: 839
Repeat patients in screened file: 103

======================================================================
REPEAT PATIENTS
======================================================================

00003110: 4 screened images
    00003110_170514ED_2 | Transverse
    00003110_E741AC77_5 | Longitudinal
    00003110_15944615_1 | Transverse
    00003110_ABBD7CBC_0 | Unknown

00003712: 3 screened images
    00003712_3B60994C_4 | Longitudinal
    00003712_DAB6E827_5 | Unknown
    00003712_755843D3_2 | Transverse

00003720: 3 screened images
    00003720_9D4FE88F_2 | Unknown
    00003720_0F75D2E5_1 | Transverse
    00003720_25838695_0 | Transverse

00004398: 3 screened images
    00004398_5C8B85B8_2 | Transverse
    00004398_60752241_1 | Transverse
    00004398_3C20BCAF_0 | Longitudinal

00004575: 3 screened images
    00004575_0418709F_4 | Longitudinal
    00004575_F8AB8366_2 | Longitudinal
    00004575_36A0B468_0 | Transverse

00001223: 3 screened images
    00001223_5EA0BD62_0 | Transverse
    00001223_866CF2B9_1 | Longitudinal
    00001223_4C9077FE_2 | Longitudinal

00001962: 2 screened images
    00001962_034B467C_1 | Transverse
    00001962_8FFD0F42_0 | Longitudinal

00002759: 2 screened images
    00002759_67AB9CA9_3 | Longitudinal
    00002759_8CE6E95E_2 | Transverse

00002564: 2 screened images
    00002564_091C8F17_1 | Transverse
    00002564_074B4873_2 | Unknown

00003648: 2 screened images
    00003648_64088A99_0 | Longitudinal
    00003648_EE87CC6D_1 | Transverse

00003108: 2 screened images
    00003108_DD20CD2D_3 | Unknown
    00003108_AE5AD07C_1 | Transverse

00001071: 2 screened images
    00001071_B2AA850F_0 | Transverse
    00001071_78AAA4D7_1 | Longitudinal

00001798: 2 screened images
    00001798_77CFF927_1 | Transverse
    00001798_0129C07F_2 | Longitudinal

00001151: 2 screened images
    00001151_FC0722AE_1 | Longitudinal
    00001151_21D3CDCF_2 | Unknown

00000333: 2 screened images
    00000333_428B7BD7_0 | Transverse
    00000333_6549FB43_2 | Longitudinal

00000724: 2 screened images
    00000724_FBC8E7E2_1 | Transverse
    00000724_0F03EA4C_2 | Unknown

00003033: 2 screened images
    00003033_6005A5A6_1 | Longitudinal
    00003033_AEE9D703_3 | Transverse

00003304: 2 screened images
    00003304_9453FFA5_2 | Transverse
    00003304_00990C42_1 | Transverse

00003730: 2 screened images
    00003730_489C1FC9_3 | Unknown
    00003730_429CBA29_5 | Longitudinal

00002678: 2 screened images
    00002678_37E14302_1 | Transverse
    00002678_7A69C716_3 | Unknown

00004607: 2 screened images
    00004607_BD4D2BF0_0 | Unknown
    00004607_016EE2DD_2 | Unknown

00002613: 2 screened images
    00002613_673E3FC4_2 | Longitudinal
    00002613_E9A907BE_0 | Longitudinal

00004594: 2 screened images
    00004594_9BFE70C2_2 | Longitudinal
    00004594_DC7CE428_1 | Transverse

00002805: 2 screened images
    00002805_C5961CCC_2 | Transverse
    00002805_72CE45D0_0 | Unknown

00003428: 2 screened images
    00003428_05CEF222_0 | Transverse
    00003428_6B106764_2 | Transverse

00004678: 2 screened images
    00004678_CC18E23B_0 | Transverse
    00004678_9BE4AE69_2 | Unknown

00003036: 2 screened images
    00003036_22FC7644_2 | Transverse
    00003036_EA94EA4C_0 | Transverse

00002241: 2 screened images
    00002241_DDC56ABB_0 | Longitudinal
    00002241_71CC4367_2 | Longitudinal

00000578: 2 screened images
    00000578_81A1AAD4_3 | Unknown
    00000578_AAD6BA89_1 | Unknown

00000968: 2 screened images
    00000968_9926DE87_1 | Longitudinal
    00000968_B8DF7DC6_0 | Transverse

00003037: 2 screened images
    00003037_084EB684_4 | Longitudinal
    00003037_03F931F6_0 | Transverse

00000261: 2 screened images
    00000261_A5969F13_3 | Longitudinal
    00000261_D6C54E9E_0 | Longitudinal

00000139: 2 screened images
    00000139_FA7E0544_0 | Longitudinal
    00000139_217557BB_1 | Unknown

00001996: 2 screened images
    00001996_3F0DCAF8_1 | Unknown
    00001996_E78BF804_2 | Longitudinal

00004034: 2 screened images
    00004034_B089D9A9_0 | Longitudinal
    00004034_86881609_2 | Longitudinal

00000372: 2 screened images
    00000372_5CF2D6D2_0 | Transverse
    00000372_2698ED21_1 | Longitudinal

00001442: 2 screened images
    00001442_3491A241_1 | Transverse
    00001442_69F47E20_0 | Longitudinal

00004621: 2 screened images
    00004621_7DFE1366_1 | Transverse
    00004621_18712D7D_0 | Longitudinal

00004002: 2 screened images
    00004002_384A6067_3 | Transverse
    00004002_156F7A84_0 | Transverse

00003782: 2 screened images
    00003782_5AB3B4CD_0 | Longitudinal
    00003782_87A3EAE4_2 | Transverse

00003706: 2 screened images
    00003706_750CC580_1 | Longitudinal
    00003706_F00964CF_2 | Transverse

00004192: 2 screened images
    00004192_448B926D_2 | Unknown
    00004192_FE7FDF70_0 | Transverse

00000798: 2 screened images
    00000798_150DC2C6_2 | Longitudinal
    00000798_5DCA5A21_1 | Unknown

00002831: 2 screened images
    00002831_BD4CCE35_1 | Longitudinal
    00002831_0D0EF506_0 | Transverse

00001759: 2 screened images
    00001759_8068E4BD_2 | Longitudinal
    00001759_59EAF97B_1 | Unknown

00003257: 2 screened images
    00003257_118E03C4_1 | Transverse
    00003257_64C38F55_2 | Longitudinal

00003982: 2 screened images
    00003982_D0C43AA7_0 | Transverse
    00003982_E6E021BE_2 | Longitudinal

00000455: 2 screened images
    00000455_5A911534_1 | Unknown
    00000455_18370D8A_0 | Transverse

00004533: 2 screened images
    00004533_F393E941_3 | Longitudinal
    00004533_88FEFE32_1 | Unknown

00002125: 2 screened images
    00002125_718DDC9D_2 | Transverse
    00002125_FA9F989F_3 | Longitudinal

00002762: 2 screened images
    00002762_CB7E4F61_2 | Transverse
    00002762_8680F020_0 | Transverse

00004689: 2 screened images
    00004689_94436886_2 | Transverse
    00004689_BD746162_0 | Transverse

00003679: 2 screened images
    00003679_68665418_1 | Unknown
    00003679_57F2439A_0 | Longitudinal

00003586: 2 screened images
    00003586_26F2435B_4 | Longitudinal
    00003586_E8976C5A_1 | Longitudinal

00002731: 2 screened images
    00002731_EF92C3E1_1 | Transverse
    00002731_53A79CB9_0 | Transverse

00002113: 2 screened images
    00002113_981A55D2_1 | Unknown
    00002113_25D340CA_0 | Transverse

00003719: 2 screened images
    00003719_6A93E40F_1 | Longitudinal
    00003719_34EB34F5_0 | Transverse

00001561: 2 screened images
    00001561_632F7DD3_1 | Longitudinal
    00001561_A689AB2E_0 | Transverse

00004276: 2 screened images
    00004276_5103C977_2 | Transverse
    00004276_534079D5_0 | Transverse

00004717: 2 screened images
    00004717_B914299D_0 | Transverse
    00004717_3F1EC379_2 | Transverse

00003682: 2 screened images
    00003682_44ADF1D3_1 | Longitudinal
    00003682_8FE17A2A_2 | Unknown

00002343: 2 screened images
    00002343_AD7AAC7C_3 | Unknown
    00002343_DDA25554_2 | Unknown

00003220: 2 screened images
    00003220_9564BD73_3 | Longitudinal
    00003220_FBF78734_1 | Transverse

00001855: 2 screened images
    00001855_53CB43EF_2 | Transverse
    00001855_FC99699B_1 | Longitudinal

00003223: 2 screened images
    00003223_12AE90AF_1 | Transverse
    00003223_970FCF82_3 | Transverse

00001334: 2 screened images
    00001334_5F3DF2B4_2 | Transverse
    00001334_CEB80814_1 | Transverse

00004059: 2 screened images
    00004059_99DB9B92_5 | Transverse
    00004059_4FB7CDB5_4 | Transverse

00003593: 2 screened images
    00003593_833876BE_3 | Unknown
    00003593_83EF0D05_0 | Unknown

00002763: 2 screened images
    00002763_F7DC6320_2 | Transverse
    00002763_7EC11016_4 | Longitudinal

00004646: 2 screened images
    00004646_85823383_3 | Transverse
    00004646_069B2B9C_0 | Transverse

00003255: 2 screened images
    00003255_EC2B28BE_2 | Longitudinal
    00003255_6A485B3E_1 | Transverse

00003155: 2 screened images
    00003155_2177994E_1 | Longitudinal
    00003155_490C9501_2 | Longitudinal

00003225: 2 screened images
    00003225_97E87A4A_0 | Longitudinal
    00003225_6027DE01_3 | Longitudinal

00004296: 2 screened images
    00004296_2CF57B69_0 | Longitudinal
    00004296_B56B102B_2 | Transverse

00002685: 2 screened images
    00002685_BEC3AF0A_3 | Unknown
    00002685_E58F203B_1 | Longitudinal

00003776: 2 screened images
    00003776_98D234E6_2 | Longitudinal
    00003776_730D9287_4 | Longitudinal

00003950: 2 screened images
    00003950_CB339AA2_6 | Transverse
    00003950_50985A09_3 | Unknown

00002962: 2 screened images
    00002962_34543322_0 | Transverse
    00002962_E773F2D3_1 | Unknown

00002615: 2 screened images
    00002615_DC4EC5C7_4 | Transverse
    00002615_7ABAF7BD_0 | Longitudinal

00004666: 2 screened images
    00004666_361BFA1A_3 | Unknown
    00004666_06483F04_0 | Transverse

00002996: 2 screened images
    00002996_D2F7979B_0 | Longitudinal
    00002996_386553E3_1 | Unknown

00000441: 2 screened images
    00000441_9A6CB7CC_0 | Transverse
    00000441_5C6613FD_3 | Longitudinal

00003770: 2 screened images
    00003770_B7EEC9F1_1 | Transverse
    00003770_34771346_2 | Longitudinal

00002990: 2 screened images
    00002990_87FE3D4D_3 | Unknown
    00002990_5F51C9F6_4 | Transverse

00003571: 2 screened images
    00003571_A08DD8C8_1 | Longitudinal
    00003571_109E8818_4 | Longitudinal

00000187: 2 screened images
    00000187_B7BAEC3B_3 | Longitudinal
    00000187_3F6254BA_1 | Transverse

00000863: 2 screened images
    00000863_78CC9CBA_0 | Longitudinal
    00000863_DF2A7A80_1 | Transverse

00002430: 2 screened images
    00002430_A2CF9696_0 | Longitudinal
    00002430_26AAA4E2_1 | Transverse

00001848: 2 screened images
    00001848_56734497_0 | Longitudinal
    00001848_A6F91F0B_2 | Longitudinal

00004572: 2 screened images
    00004572_BCC351E1_2 | Longitudinal
    00004572_9AB71188_1 | Transverse

00001175: 2 screened images
    00001175_6232E05B_1 | Longitudinal
    00001175_0A6E5184_2 | Transverse

00003372: 2 screened images
    00003372_D1DBF7E3_2 | Longitudinal
    00003372_AE5A30AC_1 | Transverse

00003116: 2 screened images
    00003116_C1213C82_2 | Transverse
    00003116_71F0EDE0_1 | Transverse

00001080: 2 screened images
    00001080_B60B08E0_2 | Longitudinal
    00001080_E8924A1B_1 | Unknown

00004066: 2 screened images
    00004066_3EB0B9C9_6 | Transverse
    00004066_27ED9D6D_4 | Longitudinal

00002368: 2 screened images
    00002368_6457CBC1_1 | Longitudinal
    00002368_F3D6AF39_0 | Transverse

00002298: 2 screened images
    00002298_486BA426_2 | Transverse
    00002298_2EDD3EB8_1 | Transverse

00000224: 2 screened images
    00000224_64C74D7C_2 | Unknown
    00000224_5A545258_1 | Transverse

00003014: 2 screened images
    00003014_22750181_1 | Longitudinal
    00003014_2B5259C8_0 | Transverse

00001900: 2 screened images
    00001900_6DE581A3_1 | Transverse
    00001900_E6FDF705_0 | Unknown

00000248: 2 screened images
    00000248_6C137413_0 | Longitudinal
    00000248_66728400_2 | Transverse

00003616: 2 screened images
    00003616_727520FA_3 | Transverse
    00003616_DF1BED36_1 | Transverse

00003312: 2 screened images
    00003312_6615241D_0 | Transverse
    00003312_707C17B4_2 | Longitudinal

In [75]:
repeat_patients

{'00001962': [{'image_id': '00001962_034B467C_1', 'view': 'Transverse'},
  {'image_id': '00001962_8FFD0F42_0', 'view': 'Longitudinal'}],
 '00002759': [{'image_id': '00002759_67AB9CA9_3', 'view': 'Longitudinal'},
  {'image_id': '00002759_8CE6E95E_2', 'view': 'Transverse'}],
 '00002564': [{'image_id': '00002564_091C8F17_1', 'view': 'Transverse'},
  {'image_id': '00002564_074B4873_2', 'view': 'Unknown'}],
 '00003648': [{'image_id': '00003648_64088A99_0', 'view': 'Longitudinal'},
  {'image_id': '00003648_EE87CC6D_1', 'view': 'Transverse'}],
 '00003108': [{'image_id': '00003108_DD20CD2D_3', 'view': 'Unknown'},
  {'image_id': '00003108_AE5AD07C_1', 'view': 'Transverse'}],
 '00001071': [{'image_id': '00001071_B2AA850F_0', 'view': 'Transverse'},
  {'image_id': '00001071_78AAA4D7_1', 'view': 'Longitudinal'}],
 '00001798': [{'image_id': '00001798_77CFF927_1', 'view': 'Transverse'},
  {'image_id': '00001798_0129C07F_2', 'view': 'Longitudinal'}],
 '00001151': [{'image_id': '00001151_FC0722AE_1', 'view': 'Longitudinal'},
  {'image_id': '00001151_21D3CDCF_2', 'view': 'Unknown'}],
 '00003712': [{'image_id': '00003712_3B60994C_4', 'view': 'Longitudinal'},
  {'image_id': '00003712_DAB6E827_5', 'view': 'Unknown'},
  {'image_id': '00003712_755843D3_2', 'view': 'Transverse'}],
 '00000333': [{'image_id': '00000333_428B7BD7_0', 'view': 'Transverse'},
  {'image_id': '00000333_6549FB43_2', 'view': 'Longitudinal'}],
 '00000724': [{'image_id': '00000724_FBC8E7E2_1', 'view': 'Transverse'},
  {'image_id': '00000724_0F03EA4C_2', 'view': 'Unknown'}],
 '00003033': [{'image_id': '00003033_6005A5A6_1', 'view': 'Longitudinal'},
  {'image_id': '00003033_AEE9D703_3', 'view': 'Transverse'}],
 '00003304': [{'image_id': '00003304_9453FFA5_2', 'view': 'Transverse'},
  {'image_id': '00003304_00990C42_1', 'view': 'Transverse'}],
 '00003730': [{'image_id': '00003730_489C1FC9_3', 'view': 'Unknown'},
  {'image_id': '00003730_429CBA29_5', 'view': 'Longitudinal'}],
 '00002678': [{'image_id': '00002678_37E14302_1', 'view': 'Transverse'},
  {'image_id': '00002678_7A69C716_3', 'view': 'Unknown'}],
 '00004607': [{'image_id': '00004607_BD4D2BF0_0', 'view': 'Unknown'},
  {'image_id': '00004607_016EE2DD_2', 'view': 'Unknown'}],
 '00002613': [{'image_id': '00002613_673E3FC4_2', 'view': 'Longitudinal'},
  {'image_id': '00002613_E9A907BE_0', 'view': 'Longitudinal'}],
 '00003110': [{'image_id': '00003110_170514ED_2', 'view': 'Transverse'},
  {'image_id': '00003110_E741AC77_5', 'view': 'Longitudinal'},
  {'image_id': '00003110_15944615_1', 'view': 'Transverse'},
  {'image_id': '00003110_ABBD7CBC_0', 'view': 'Unknown'}],
 '00004594': [{'image_id': '00004594_9BFE70C2_2', 'view': 'Longitudinal'},
  {'image_id': '00004594_DC7CE428_1', 'view': 'Transverse'}],
 '00002805': [{'image_id': '00002805_C5961CCC_2', 'view': 'Transverse'},
  {'image_id': '00002805_72CE45D0_0', 'view': 'Unknown'}],
 '00003428': [{'image_id': '00003428_05CEF222_0', 'view': 'Transverse'},
  {'image_id': '00003428_6B106764_2', 'view': 'Transverse'}],
 '00004678': [{'image_id': '00004678_CC18E23B_0', 'view': 'Transverse'},
  {'image_id': '00004678_9BE4AE69_2', 'view': 'Unknown'}],
 '00003036': [{'image_id': '00003036_22FC7644_2', 'view': 'Transverse'},
  {'image_id': '00003036_EA94EA4C_0', 'view': 'Transverse'}],
 '00002241': [{'image_id': '00002241_DDC56ABB_0', 'view': 'Longitudinal'},
  {'image_id': '00002241_71CC4367_2', 'view': 'Longitudinal'}],
 '00000578': [{'image_id': '00000578_81A1AAD4_3', 'view': 'Unknown'},
  {'image_id': '00000578_AAD6BA89_1', 'view': 'Unknown'}],
 '00000968': [{'image_id': '00000968_9926DE87_1', 'view': 'Longitudinal'},
  {'image_id': '00000968_B8DF7DC6_0', 'view': 'Transverse'}],
 '00003037': [{'image_id': '00003037_084EB684_4', 'view': 'Longitudinal'},
  {'image_id': '00003037_03F931F6_0', 'view': 'Transverse'}],
 '00000261': [{'image_id': '00000261_A5969F13_3', 'view': 'Longitudinal'},
  {'image_id': '00000261_D6C54E9E_0', 'view': 'Longitudinal'}],
 '00000139': [{'image_id': '00000139_FA7E0544_0', 'view': 'Longitudinal'},
  {'image_id': '00000139_217557BB_1', 'view': 'Unknown'}],
 '00001996': [{'image_id': '00001996_3F0DCAF8_1', 'view': 'Unknown'},
  {'image_id': '00001996_E78BF804_2', 'view': 'Longitudinal'}],
 '00004034': [{'image_id': '00004034_B089D9A9_0', 'view': 'Longitudinal'},
  {'image_id': '00004034_86881609_2', 'view': 'Longitudinal'}],
 '00000372': [{'image_id': '00000372_5CF2D6D2_0', 'view': 'Transverse'},
  {'image_id': '00000372_2698ED21_1', 'view': 'Longitudinal'}],
 '00001442': [{'image_id': '00001442_3491A241_1', 'view': 'Transverse'},
  {'image_id': '00001442_69F47E20_0', 'view': 'Longitudinal'}],
 '00003720': [{'image_id': '00003720_9D4FE88F_2', 'view': 'Unknown'},
  {'image_id': '00003720_0F75D2E5_1', 'view': 'Transverse'},
  {'image_id': '00003720_25838695_0', 'view': 'Transverse'}],
 '00004621': [{'image_id': '00004621_7DFE1366_1', 'view': 'Transverse'},
  {'image_id': '00004621_18712D7D_0', 'view': 'Longitudinal'}],
 '00004002': [{'image_id': '00004002_384A6067_3', 'view': 'Transverse'},
  {'image_id': '00004002_156F7A84_0', 'view': 'Transverse'}],
 '00003782': [{'image_id': '00003782_5AB3B4CD_0', 'view': 'Longitudinal'},
  {'image_id': '00003782_87A3EAE4_2', 'view': 'Transverse'}],
 '00003706': [{'image_id': '00003706_750CC580_1', 'view': 'Longitudinal'},
  {'image_id': '00003706_F00964CF_2', 'view': 'Transverse'}],
 '00004192': [{'image_id': '00004192_448B926D_2', 'view': 'Unknown'},
  {'image_id': '00004192_FE7FDF70_0', 'view': 'Transverse'}],
 '00000798': [{'image_id': '00000798_150DC2C6_2', 'view': 'Longitudinal'},
  {'image_id': '00000798_5DCA5A21_1', 'view': 'Unknown'}],
 '00002831': [{'image_id': '00002831_BD4CCE35_1', 'view': 'Longitudinal'},
  {'image_id': '00002831_0D0EF506_0', 'view': 'Transverse'}],
 '00001759': [{'image_id': '00001759_8068E4BD_2', 'view': 'Longitudinal'},
  {'image_id': '00001759_59EAF97B_1', 'view': 'Unknown'}],
 '00003257': [{'image_id': '00003257_118E03C4_1', 'view': 'Transverse'},
  {'image_id': '00003257_64C38F55_2', 'view': 'Longitudinal'}],
 '00003982': [{'image_id': '00003982_D0C43AA7_0', 'view': 'Transverse'},
  {'image_id': '00003982_E6E021BE_2', 'view': 'Longitudinal'}],
 '00000455': [{'image_id': '00000455_5A911534_1', 'view': 'Unknown'},
  {'image_id': '00000455_18370D8A_0', 'view': 'Transverse'}],
 '00004533': [{'image_id': '00004533_F393E941_3', 'view': 'Longitudinal'},
  {'image_id': '00004533_88FEFE32_1', 'view': 'Unknown'}],
 '00002125': [{'image_id': '00002125_718DDC9D_2', 'view': 'Transverse'},
  {'image_id': '00002125_FA9F989F_3', 'view': 'Longitudinal'}],
 '00002762': [{'image_id': '00002762_CB7E4F61_2', 'view': 'Transverse'},
  {'image_id': '00002762_8680F020_0', 'view': 'Transverse'}],
 '00004689': [{'image_id': '00004689_94436886_2', 'view': 'Transverse'},
  {'image_id': '00004689_BD746162_0', 'view': 'Transverse'}],
 '00003679': [{'image_id': '00003679_68665418_1', 'view': 'Unknown'},
  {'image_id': '00003679_57F2439A_0', 'view': 'Longitudinal'}],
 '00003586': [{'image_id': '00003586_26F2435B_4', 'view': 'Longitudinal'},
  {'image_id': '00003586_E8976C5A_1', 'view': 'Longitudinal'}],
 '00002731': [{'image_id': '00002731_EF92C3E1_1', 'view': 'Transverse'},
  {'image_id': '00002731_53A79CB9_0', 'view': 'Transverse'}],
 '00002113': [{'image_id': '00002113_981A55D2_1', 'view': 'Unknown'},
  {'image_id': '00002113_25D340CA_0', 'view': 'Transverse'}],
 '00003719': [{'image_id': '00003719_6A93E40F_1', 'view': 'Longitudinal'},
  {'image_id': '00003719_34EB34F5_0', 'view': 'Transverse'}],
 '00001561': [{'image_id': '00001561_632F7DD3_1', 'view': 'Longitudinal'},
  {'image_id': '00001561_A689AB2E_0', 'view': 'Transverse'}],
 '00004276': [{'image_id': '00004276_5103C977_2', 'view': 'Transverse'},
  {'image_id': '00004276_534079D5_0', 'view': 'Transverse'}],
 '00004398': [{'image_id': '00004398_5C8B85B8_2', 'view': 'Transverse'},
  {'image_id': '00004398_60752241_1', 'view': 'Transverse'},
  {'image_id': '00004398_3C20BCAF_0', 'view': 'Longitudinal'}],
 '00004717': [{'image_id': '00004717_B914299D_0', 'view': 'Transverse'},
  {'image_id': '00004717_3F1EC379_2', 'view': 'Transverse'}],
 '00003682': [{'image_id': '00003682_44ADF1D3_1', 'view': 'Longitudinal'},
  {'image_id': '00003682_8FE17A2A_2', 'view': 'Unknown'}],
 '00002343': [{'image_id': '00002343_AD7AAC7C_3', 'view': 'Unknown'},
  {'image_id': '00002343_DDA25554_2', 'view': 'Unknown'}],
 '00003220': [{'image_id': '00003220_9564BD73_3', 'view': 'Longitudinal'},
  {'image_id': '00003220_FBF78734_1', 'view': 'Transverse'}],
 '00001855': [{'image_id': '00001855_53CB43EF_2', 'view': 'Transverse'},
  {'image_id': '00001855_FC99699B_1', 'view': 'Longitudinal'}],
 '00003223': [{'image_id': '00003223_12AE90AF_1', 'view': 'Transverse'},
  {'image_id': '00003223_970FCF82_3', 'view': 'Transverse'}],
 '00004575': [{'image_id': '00004575_0418709F_4', 'view': 'Longitudinal'},
  {'image_id': '00004575_F8AB8366_2', 'view': 'Longitudinal'},
  {'image_id': '00004575_36A0B468_0', 'view': 'Transverse'}],
 '00001334': [{'image_id': '00001334_5F3DF2B4_2', 'view': 'Transverse'},
  {'image_id': '00001334_CEB80814_1', 'view': 'Transverse'}],
 '00004059': [{'image_id': '00004059_99DB9B92_5', 'view': 'Transverse'},
  {'image_id': '00004059_4FB7CDB5_4', 'view': 'Transverse'}],
 '00003593': [{'image_id': '00003593_833876BE_3', 'view': 'Unknown'},
  {'image_id': '00003593_83EF0D05_0', 'view': 'Unknown'}],
 '00002763': [{'image_id': '00002763_F7DC6320_2', 'view': 'Transverse'},
  {'image_id': '00002763_7EC11016_4', 'view': 'Longitudinal'}],
 '00004646': [{'image_id': '00004646_85823383_3', 'view': 'Transverse'},
  {'image_id': '00004646_069B2B9C_0', 'view': 'Transverse'}],
 '00003255': [{'image_id': '00003255_EC2B28BE_2', 'view': 'Longitudinal'},
  {'image_id': '00003255_6A485B3E_1', 'view': 'Transverse'}],
 '00001223': [{'image_id': '00001223_5EA0BD62_0', 'view': 'Transverse'},
  {'image_id': '00001223_866CF2B9_1', 'view': 'Longitudinal'},
  {'image_id': '00001223_4C9077FE_2', 'view': 'Longitudinal'}],
 '00003155': [{'image_id': '00003155_2177994E_1', 'view': 'Longitudinal'},
  {'image_id': '00003155_490C9501_2', 'view': 'Longitudinal'}],
 '00003225': [{'image_id': '00003225_97E87A4A_0', 'view': 'Longitudinal'},
  {'image_id': '00003225_6027DE01_3', 'view': 'Longitudinal'}],
 '00004296': [{'image_id': '00004296_2CF57B69_0', 'view': 'Longitudinal'},
  {'image_id': '00004296_B56B102B_2', 'view': 'Transverse'}],
 '00002685': [{'image_id': '00002685_BEC3AF0A_3', 'view': 'Unknown'},
  {'image_id': '00002685_E58F203B_1', 'view': 'Longitudinal'}],
 '00003776': [{'image_id': '00003776_98D234E6_2', 'view': 'Longitudinal'},
  {'image_id': '00003776_730D9287_4', 'view': 'Longitudinal'}],
 '00003950': [{'image_id': '00003950_CB339AA2_6', 'view': 'Transverse'},
  {'image_id': '00003950_50985A09_3', 'view': 'Unknown'}],
 '00002962': [{'image_id': '00002962_34543322_0', 'view': 'Transverse'},
  {'image_id': '00002962_E773F2D3_1', 'view': 'Unknown'}],
 '00002615': [{'image_id': '00002615_DC4EC5C7_4', 'view': 'Transverse'},
  {'image_id': '00002615_7ABAF7BD_0', 'view': 'Longitudinal'}],
 '00004666': [{'image_id': '00004666_361BFA1A_3', 'view': 'Unknown'},
  {'image_id': '00004666_06483F04_0', 'view': 'Transverse'}],
 '00002996': [{'image_id': '00002996_D2F7979B_0', 'view': 'Longitudinal'},
  {'image_id': '00002996_386553E3_1', 'view': 'Unknown'}],
 '00000441': [{'image_id': '00000441_9A6CB7CC_0', 'view': 'Transverse'},
  {'image_id': '00000441_5C6613FD_3', 'view': 'Longitudinal'}],
 '00003770': [{'image_id': '00003770_B7EEC9F1_1', 'view': 'Transverse'},
  {'image_id': '00003770_34771346_2', 'view': 'Longitudinal'}],
 '00002990': [{'image_id': '00002990_87FE3D4D_3', 'view': 'Unknown'},
  {'image_id': '00002990_5F51C9F6_4', 'view': 'Transverse'}],
 '00003571': [{'image_id': '00003571_A08DD8C8_1', 'view': 'Longitudinal'},
  {'image_id': '00003571_109E8818_4', 'view': 'Longitudinal'}],
 '00000187': [{'image_id': '00000187_B7BAEC3B_3', 'view': 'Longitudinal'},
  {'image_id': '00000187_3F6254BA_1', 'view': 'Transverse'}],
 '00000863': [{'image_id': '00000863_78CC9CBA_0', 'view': 'Longitudinal'},
  {'image_id': '00000863_DF2A7A80_1', 'view': 'Transverse'}],
 '00002430': [{'image_id': '00002430_A2CF9696_0', 'view': 'Longitudinal'},
  {'image_id': '00002430_26AAA4E2_1', 'view': 'Transverse'}],
 '00001848': [{'image_id': '00001848_56734497_0', 'view': 'Longitudinal'},
  {'image_id': '00001848_A6F91F0B_2', 'view': 'Longitudinal'}],
 '00004572': [{'image_id': '00004572_BCC351E1_2', 'view': 'Longitudinal'},
  {'image_id': '00004572_9AB71188_1', 'view': 'Transverse'}],
 '00001175': [{'image_id': '00001175_6232E05B_1', 'view': 'Longitudinal'},
  {'image_id': '00001175_0A6E5184_2', 'view': 'Transverse'}],
 '00003372': [{'image_id': '00003372_D1DBF7E3_2', 'view': 'Longitudinal'},
  {'image_id': '00003372_AE5A30AC_1', 'view': 'Transverse'}],
 '00003116': [{'image_id': '00003116_C1213C82_2', 'view': 'Transverse'},
  {'image_id': '00003116_71F0EDE0_1', 'view': 'Transverse'}],
 '00001080': [{'image_id': '00001080_B60B08E0_2', 'view': 'Longitudinal'},
  {'image_id': '00001080_E8924A1B_1', 'view': 'Unknown'}],
 '00004066': [{'image_id': '00004066_3EB0B9C9_6', 'view': 'Transverse'},
  {'image_id': '00004066_27ED9D6D_4', 'view': 'Longitudinal'}],
 '00002368': [{'image_id': '00002368_6457CBC1_1', 'view': 'Longitudinal'},
  {'image_id': '00002368_F3D6AF39_0', 'view': 'Transverse'}],
 '00002298': [{'image_id': '00002298_486BA426_2', 'view': 'Transverse'},
  {'image_id': '00002298_2EDD3EB8_1', 'view': 'Transverse'}],
 '00000224': [{'image_id': '00000224_64C74D7C_2', 'view': 'Unknown'},
  {'image_id': '00000224_5A545258_1', 'view': 'Transverse'}],
 '00003014': [{'image_id': '00003014_22750181_1', 'view': 'Longitudinal'},
  {'image_id': '00003014_2B5259C8_0', 'view': 'Transverse'}],
 '00001900': [{'image_id': '00001900_6DE581A3_1', 'view': 'Transverse'},
  {'image_id': '00001900_E6FDF705_0', 'view': 'Unknown'}],
 '00000248': [{'image_id': '00000248_6C137413_0', 'view': 'Longitudinal'},
  {'image_id': '00000248_66728400_2', 'view': 'Transverse'}],
 '00003616': [{'image_id': '00003616_727520FA_3', 'view': 'Transverse'},
  {'image_id': '00003616_DF1BED36_1', 'view': 'Transverse'}],
 '00003312': [{'image_id': '00003312_6615241D_0', 'view': 'Transverse'},
  {'image_id': '00003312_707C17B4_2', 'view': 'Longitudinal'}]}

In [76]:
distribution = Counter(
    len(images)
    for images in patients.values()
)

print("\nScreened images per patient:")

for n_images, n_patients in sorted(
    distribution.items()
):
    print(
        f"{n_images} image(s): "
        f"{n_patients} patient(s)"
    )

Screened images per patient:
1 image(s): 736 patient(s)
2 image(s): 97 patient(s)
3 image(s): 5 patient(s)
4 image(s): 1 patient(s)

In [77]:
patients

defaultdict(list,
            {'00003307': [{'image_id': '00003307_17EE0585_0',
               'view': 'Transverse'}],
             '00003723': [{'image_id': '00003723_CCF3845C_2',
               'view': 'Longitudinal'}],
             '00001962': [{'image_id': '00001962_034B467C_1',
               'view': 'Transverse'},
              {'image_id': '00001962_8FFD0F42_0', 'view': 'Longitudinal'}],
             '00002300': [{'image_id': '00002300_E60B804B_0',
               'view': 'Transverse'}],
             '00003387': [{'image_id': '00003387_76B10567_2',
               'view': 'Transverse'}],
             '00001362': [{'image_id': '00001362_5EA700B7_0',
               'view': 'Transverse'}],
             '00002722': [{'image_id': '00002722_0B61FD23_2',
               'view': 'Longitudinal'}],
             '00000353': [{'image_id': '00000353_883F0C38_0',
               'view': 'Longitudinal'}],
             '00003891': [{'image_id': '00003891_D1D14835_4',
               'view': 'Unknown'}],
             '00004035': [{'image_id': '00004035_67EE1254_1',
               'view': 'Transverse'}],
             '00000689': [{'image_id': '00000689_5DDC80B8_1',
               'view': 'Transverse'}],
             '00000244': [{'image_id': '00000244_B8CF86FD_0',
               'view': 'Longitudinal'}],
             '00003035': [{'image_id': '00003035_B50CCC3A_2',
               'view': 'Transverse'}],
             '00000299': [{'image_id': '00000299_9987EB8C_0',
               'view': 'Longitudinal'}],
             '00003118': [{'image_id': '00003118_109FF640_3',
               'view': 'Transverse'}],
             '00003495': [{'image_id': '00003495_9FD9BD0B_1',
               'view': 'Longitudinal'}],
             '00002706': [{'image_id': '00002706_EFC889ED_0',
               'view': 'Transverse'}],
             '00000498': [{'image_id': '00000498_CA1667E9_3',
               'view': 'Transverse'}],
             '00000676': [{'image_id': '00000676_3AF33F07_2',
               'view': 'Transverse'}],
             '00003496': [{'image_id': '00003496_52E2F6E5_0',
               'view': 'Longitudinal'}],
             '00000712': [{'image_id': '00000712_F5B42CFA_0',
               'view': 'Longitudinal'}],
             '00003869': [{'image_id': '00003869_C35ED365_3',
               'view': 'Longitudinal'}],
             '00000320': [{'image_id': '00000320_AC171F00_1',
               'view': 'Unknown'}],
             '00003348': [{'image_id': '00003348_C01AC6F5_1',
               'view': 'Longitudinal'}],
             '00002139': [{'image_id': '00002139_F9A97993_0',
               'view': 'Transverse'}],
             '00002626': [{'image_id': '00002626_C78A7D1B_2',
               'view': 'Unknown'}],
             '00000141': [{'image_id': '00000141_CFD4B94F_0',
               'view': 'Transverse'}],
             '00002897': [{'image_id': '00002897_3E95E8F3_1',
               'view': 'Transverse'}],
             '00002008': [{'image_id': '00002008_8AC4100D_0',
               'view': 'Transverse'}],
             '00002759': [{'image_id': '00002759_67AB9CA9_3',
               'view': 'Longitudinal'},
              {'image_id': '00002759_8CE6E95E_2', 'view': 'Transverse'}],
             '00001172': [{'image_id': '00001172_34E4745B_1',
               'view': 'Transverse'}],
             '00002329': [{'image_id': '00002329_12692A34_0',
               'view': 'Longitudinal'}],
             '00001531': [{'image_id': '00001531_6C6E8F29_0',
               'view': 'Longitudinal'}],
             '00003422': [{'image_id': '00003422_41791C2E_2',
               'view': 'Transverse'}],
             '00003992': [{'image_id': '00003992_E19E84B3_1',
               'view': 'Longitudinal'}],
             '00002980': [{'image_id': '00002980_5A1D52F5_3',
               'view': 'Transverse'}],
             '00002564': [{'image_id': '00002564_091C8F17_1',
               'view': 'Transverse'},
              {'image_id': '00002564_074B4873_2', 'view': 'Unknown'}],
             '00003648': [{'image_id': '00003648_64088A99_0',
               'view': 'Longitudinal'},
              {'image_id': '00003648_EE87CC6D_1', 'view': 'Transverse'}],
             '00003108': [{'image_id': '00003108_DD20CD2D_3',
               'view': 'Unknown'},
              {'image_id': '00003108_AE5AD07C_1', 'view': 'Transverse'}],
             '00001071': [{'image_id': '00001071_B2AA850F_0',
               'view': 'Transverse'},
              {'image_id': '00001071_78AAA4D7_1', 'view': 'Longitudinal'}],
             '00001798': [{'image_id': '00001798_77CFF927_1',
               'view': 'Transverse'},
              {'image_id': '00001798_0129C07F_2', 'view': 'Longitudinal'}],
             '00000239': [{'image_id': '00000239_C2174724_1',
               'view': 'Transverse'}],
             '00004739': [{'image_id': '00004739_7A5FDE47_1',
               'view': 'Transverse'}],
             '00003302': [{'image_id': '00003302_980F1918_3',
               'view': 'Longitudinal'}],
             '00004556': [{'image_id': '00004556_B4A47A0E_0',
               'view': 'Transverse'}],
             '00003755': [{'image_id': '00003755_E4FB4AE4_0',
               'view': 'Transverse'}],
             '00001151': [{'image_id': '00001151_FC0722AE_1',
               'view': 'Longitudinal'},
              {'image_id': '00001151_21D3CDCF_2', 'view': 'Unknown'}],
             '00003712': [{'image_id': '00003712_3B60994C_4',
               'view': 'Longitudinal'},
              {'image_id': '00003712_DAB6E827_5', 'view': 'Unknown'},
              {'image_id': '00003712_755843D3_2', 'view': 'Transverse'}],
             '00002317': [{'image_id': '00002317_7B3E6772_0',
               'view': 'Transverse'}],
             '00001446': [{'image_id': '00001446_E2085904_0',
               'view': 'Transverse'}],
             '00000333': [{'image_id': '00000333_428B7BD7_0',
               'view': 'Transverse'},
              {'image_id': '00000333_6549FB43_2', 'view': 'Longitudinal'}],
             '00004582': [{'image_id': '00004582_A326F9AB_2',
               'view': 'Longitudinal'}],
             '00002782': [{'image_id': '00002782_11E2978D_0',
               'view': 'Transverse'}],
             '00000705': [{'image_id': '00000705_A5A99D8A_2',
               'view': 'Longitudinal'}],
             '00000724': [{'image_id': '00000724_FBC8E7E2_1',
               'view': 'Transverse'},
              {'image_id': '00000724_0F03EA4C_2', 'view': 'Unknown'}],
             '00002376': [{'image_id': '00002376_F529823F_3',
               'view': 'Transverse'}],
             '00003033': [{'image_id': '00003033_6005A5A6_1',
               'view': 'Longitudinal'},
              {'image_id': '00003033_AEE9D703_3', 'view': 'Transverse'}],
             '00000788': [{'image_id': '00000788_8E42B3C9_1',
               'view': 'Longitudinal'}],
             '00001225': [{'image_id': '00001225_EF55F128_4',
               'view': 'Transverse'}],
             '00004021': [{'image_id': '00004021_F8E204D0_0',
               'view': 'Transverse'}],
             '00003304': [{'image_id': '00003304_9453FFA5_2',
               'view': 'Transverse'},
              {'image_id': '00003304_00990C42_1', 'view': 'Transverse'}],
             '00003730': [{'image_id': '00003730_489C1FC9_3',
               'view': 'Unknown'},
              {'image_id': '00003730_429CBA29_5', 'view': 'Longitudinal'}],
             '00001907': [{'image_id': '00001907_D695209F_0',
               'view': 'Longitudinal'}],
             '00002678': [{'image_id': '00002678_37E14302_1',
               'view': 'Transverse'},
              {'image_id': '00002678_7A69C716_3', 'view': 'Unknown'}],
             '00000631': [{'image_id': '00000631_4B36FAA9_1',
               'view': 'Longitudinal'}],
             '00001620': [{'image_id': '00001620_61BED965_1',
               'view': 'Transverse'}],
             '00003494': [{'image_id': '00003494_999DB6DA_1',
               'view': 'Transverse'}],
             '00004278': [{'image_id': '00004278_53FECB07_2',
               'view': 'Unknown'}],
             '00000460': [{'image_id': '00000460_C8B2D1A0_4',
               'view': 'Longitudinal'}],
             '00004607': [{'image_id': '00004607_BD4D2BF0_0',
               'view': 'Unknown'},
              {'image_id': '00004607_016EE2DD_2', 'view': 'Unknown'}],
             '00000496': [{'image_id': '00000496_9E7B6770_3',
               'view': 'Unknown'}],
             '00002100': [{'image_id': '00002100_C37DE743_0',
               'view': 'Longitudinal'}],
             '00002613': [{'image_id': '00002613_673E3FC4_2',
               'view': 'Longitudinal'},
              {'image_id': '00002613_E9A907BE_0', 'view': 'Longitudinal'}],
             '00000583': [{'image_id': '00000583_45139B88_2',
               'view': 'Longitudinal'}],
             '00003110': [{'image_id': '00003110_170514ED_2',
               'view': 'Transverse'},
              {'image_id': '00003110_E741AC77_5', 'view': 'Longitudinal'},
              {'image_id': '00003110_15944615_1', 'view': 'Transverse'},
              {'image_id': '00003110_ABBD7CBC_0', 'view': 'Unknown'}],
             '00002095': [{'image_id': '00002095_8D0CED5D_0',
               'view': 'Longitudinal'}],
             '00003376': [{'image_id': '00003376_0AA6CAF2_0',
               'view': 'Transverse'}],
             '00002006': [{'image_id': '00002006_4D52E291_1',
               'view': 'Longitudinal'}],
             '00004594': [{'image_id': '00004594_9BFE70C2_2',
               'view': 'Longitudinal'},
              {'image_id': '00004594_DC7CE428_1', 'view': 'Transverse'}],
             '00002386': [{'image_id': '00002386_CF8EB892_1',
               'view': 'Transverse'}],
             '00001429': [{'image_id': '00001429_2EFE0FB3_1',
               'view': 'Longitudinal'}],
             '00003772': [{'image_id': '00003772_CA14876A_2',
               'view': 'Transverse'}],
             '00002171': [{'image_id': '00002171_08AE5477_2',
               'view': 'Longitudinal'}],
             '00001249': [{'image_id': '00001249_004EE4EE_0',
               'view': 'Longitudinal'}],
             '00001196': [{'image_id': '00001196_C45D51FD_2',
               'view': 'Longitudinal'}],
             '00003239': [{'image_id': '00003239_91D8199A_0',
               'view': 'Longitudinal'}],
             '00002857': [{'image_id': '00002857_28EA146D_3',
               'view': 'Transverse'}],
             '00001989': [{'image_id': '00001989_B4D68A2B_2',
               'view': 'Longitudinal'}],
             '00001394': [{'image_id': '00001394_1ADDCE41_2',
               'view': 'Longitudinal'}],
             '00000852': [{'image_id': '00000852_E9846CBF_1',
               'view': 'Transverse'}],
             '00003666': [{'image_id': '00003666_1DE085E0_1',
               'view': 'Longitudinal'}],
             '00002805': [{'image_id': '00002805_C5961CCC_2',
               'view': 'Transverse'},
              {'image_id': '00002805_72CE45D0_0', 'view': 'Unknown'}],
             '00000495': [{'image_id': '00000495_52AA3323_3',
               'view': 'Longitudinal'}],
             '00003428': [{'image_id': '00003428_05CEF222_0',
               'view': 'Transverse'},
              {'image_id': '00003428_6B106764_2', 'view': 'Transverse'}],
             '00002702': [{'image_id': '00002702_D4C32BC9_0',
               'view': 'Longitudinal'}],
             '00003521': [{'image_id': '00003521_A3069EEF_1',
               'view': 'Transverse'}],
             '00001053': [{'image_id': '00001053_4E15B104_3',
               'view': 'Transverse'}],
             '00003816': [{'image_id': '00003816_81ADAF2E_1',
               'view': 'Longitudinal'}],
             '00004058': [{'image_id': '00004058_01CCEBC6_9',
               'view': 'Longitudinal'}],
             '00003567': [{'image_id': '00003567_508FEF53_1',
               'view': 'Transverse'}],
             '00000345': [{'image_id': '00000345_7C72D738_0',
               'view': 'Longitudinal'}],
             '00001870': [{'image_id': '00001870_8B0633C9_1',
               'view': 'Longitudinal'}],
             '00003251': [{'image_id': '00003251_586CE88F_3',
               'view': 'Transverse'}],
             '00004678': [{'image_id': '00004678_CC18E23B_0',
               'view': 'Transverse'},
              {'image_id': '00004678_9BE4AE69_2', 'view': 'Unknown'}],
             '00003292': [{'image_id': '00003292_B5C3176F_2',
               'view': 'Longitudinal'}],
             '00003873': [{'image_id': '00003873_1522E24A_2',
               'view': 'Longitudinal'}],
             '00004015': [{'image_id': '00004015_12245EE4_0',
               'view': 'Transverse'}],
             '00003036': [{'image_id': '00003036_22FC7644_2',
               'view': 'Transverse'},
              {'image_id': '00003036_EA94EA4C_0', 'view': 'Transverse'}],
             '00002924': [{'image_id': '00002924_95D913E7_1',
               'view': 'Transverse'}],
             '00004680': [{'image_id': '00004680_FC71DCBB_3',
               'view': 'Transverse'}],
             '00003743': [{'image_id': '00003743_2235ECB8_0',
               'view': 'Transverse'}],
             '00001205': [{'image_id': '00001205_B202DECD_1',
               'view': 'Transverse'}],
             '00004009': [{'image_id': '00004009_7AB5E6CF_1',
               'view': 'Transverse'}],
             '00002241': [{'image_id': '00002241_DDC56ABB_0',
               'view': 'Longitudinal'},
              {'image_id': '00002241_71CC4367_2', 'view': 'Longitudinal'}],
             '00000578': [{'image_id': '00000578_81A1AAD4_3',
               'view': 'Unknown'},
              {'image_id': '00000578_AAD6BA89_1', 'view': 'Unknown'}],
             '00000968': [{'image_id': '00000968_9926DE87_1',
               'view': 'Longitudinal'},
              {'image_id': '00000968_B8DF7DC6_0', 'view': 'Transverse'}],
             '00003471': [{'image_id': '00003471_CB3A5690_0',
               'view': 'Transverse'}],
             '00001343': [{'image_id': '00001343_E4E2D9FA_0',
               'view': 'Transverse'}],
             '00001321': [{'image_id': '00001321_5D10EC11_0',
               'view': 'Transverse'}],
             '00002147': [{'image_id': '00002147_97733F34_1',
               'view': 'Transverse'}],
             '00003846': [{'image_id': '00003846_9B615DC6_3',
               'view': 'Transverse'}],
             '00003037': [{'image_id': '00003037_084EB684_4',
               'view': 'Longitudinal'},
              {'image_id': '00003037_03F931F6_0', 'view': 'Transverse'}],
             '00004056': [{'image_id': '00004056_E129D4B4_6',
               'view': 'Longitudinal'}],
             '00003961': [{'image_id': '00003961_E74DF424_0',
               'view': 'Transverse'}],
             '00003339': [{'image_id': '00003339_2E1B6AA4_1',
               'view': 'Longitudinal'}],
             '00001533': [{'image_id': '00001533_B6B4E396_1',
               'view': 'Transverse'}],
             '00004756': [{'image_id': '00004756_537CCD1B_2',
               'view': 'Unknown'}],
             '00000773': [{'image_id': '00000773_AC9FAB14_0',
               'view': 'Longitudinal'}],
             '00001452': [{'image_id': '00001452_F32D3C02_0',
               'view': 'Unknown'}],
             '00004711': [{'image_id': '00004711_680C20B8_1',
               'view': 'Transverse'}],
             '00004584': [{'image_id': '00004584_CD17F323_1',
               'view': 'Longitudinal'}],
             '00003331': [{'image_id': '00003331_F25E0CE3_0',
               'view': 'Longitudinal'}],
             '00000261': [{'image_id': '00000261_A5969F13_3',
               'view': 'Longitudinal'},
              {'image_id': '00000261_D6C54E9E_0', 'view': 'Longitudinal'}],
             '00002788': [{'image_id': '00002788_FCF8AC51_1',
               'view': 'Longitudinal'}],
             '00002434': [{'image_id': '00002434_4CF40A72_1',
               'view': 'Longitudinal'}],
             '00000875': [{'image_id': '00000875_8FB50796_0',
               'view': 'Longitudinal'}],
             '00003135': [{'image_id': '00003135_80CF98B5_2',
               'view': 'Transverse'}],
             '00002768': [{'image_id': '00002768_657319E5_0',
               'view': 'Transverse'}],
             '00001666': [{'image_id': '00001666_20BDD798_1',
               'view': 'Longitudinal'}],
             '00000870': [{'image_id': '00000870_BCD3F9C8_0',
               'view': 'Longitudinal'}],
             '00002638': [{'image_id': '00002638_BA1F0377_0',
               'view': 'Transverse'}],
             '00002480': [{'image_id': '00002480_AC7C4D6D_1',
               'view': 'Longitudinal'}],
             '00004031': [{'image_id': '00004031_84075C6C_0',
               'view': 'Unknown'}],
             '00003091': [{'image_id': '00003091_666CFE4C_2',
               'view': 'Transverse'}],
             '00001803': [{'image_id': '00001803_6379CB70_0',
               'view': 'Transverse'}],
             '00000577': [{'image_id': '00000577_CF656C90_0',
               'view': 'Longitudinal'}],
             '00003913': [{'image_id': '00003913_1289FC75_0',
               'view': 'Longitudinal'}],
             '00002749': [{'image_id': '00002749_1784B49C_1',
               'view': 'Transverse'}],
             '00003868': [{'image_id': '00003868_B2DFC15A_1',
               'view': 'Transverse'}],
             '00004038': [{'image_id': '00004038_E562B24C_0',
               'view': 'Transverse'}],
             '00002251': [{'image_id': '00002251_7CA21CDC_1',
               'view': 'Longitudinal'}],
             '00000139': [{'image_id': '00000139_FA7E0544_0',
               'view': 'Longitudinal'},
              {'image_id': '00000139_217557BB_1', 'view': 'Unknown'}],
             '00001905': [{'image_id': '00001905_FE15239B_0',
               'view': 'Transverse'}],
             '00000713': [{'image_id': '00000713_D6CDBB67_1',
               'view': 'Unknown'}],
             '00003024': [{'image_id': '00003024_FAC23E95_1',
               'view': 'Unknown'}],
             '00003566': [{'image_id': '00003566_E5E9B40A_0',
               'view': 'Transverse'}],
             '00003748': [{'image_id': '00003748_16F432E0_1',
               'view': 'Transverse'}],
             '00001043': [{'image_id': '00001043_53DDFED0_1',
               'view': 'Longitudinal'}],
             '00003587': [{'image_id': '00003587_7E59F0F0_1',
               'view': 'Longitudinal'}],
             '00001540': [{'image_id': '00001540_A85A7F7A_0',
               'view': 'Transverse'}],
             '00001657': [{'image_id': '00001657_2EBD661C_0',
               'view': 'Longitudinal'}],
             '00001931': [{'image_id': '00001931_D0BF5320_1',
               'view': 'Transverse'}],
             '00000984': [{'image_id': '00000984_6A14FD3A_0',
               'view': 'Longitudinal'}],
             '00001827': [{'image_id': '00001827_249CFE15_1',
               'view': 'Longitudinal'}],
             '00002552': [{'image_id': '00002552_1B25A5FC_1',
               'view': 'Unknown'}],
             '00002604': [{'image_id': '00002604_DB762E8A_0',
               'view': 'Longitudinal'}],
             '00000152': [{'image_id': '00000152_FED1C9E5_2',
               'view': 'Transverse'}],
             '00002908': [{'image_id': '00002908_A6E0BBFF_0',
               'view': 'Longitudinal'}],
             '00001388': [{'image_id': '00001388_E9B6B324_1',
               'view': 'Longitudinal'}],
             '00000440': [{'image_id': '00000440_5DC20C46_2',
               'view': 'Unknown'}],
             '00003433': [{'image_id': '00003433_CF6255AE_0',
               'view': 'Longitudinal'}],
             '00000298': [{'image_id': '00000298_233B954B_2',
               'view': 'Longitudinal'}],
             '00003678': [{'image_id': '00003678_6B9ECDA5_0',
               'view': 'Transverse'}],
             '00003358': [{'image_id': '00003358_EED38051_3',

In [78]:
for patient in patients.items():
    print(f"\nPatient ID: {patient[0]}")
    print(f"\nImages: {patient[1]}")

Patient ID: 00003307

Images: [{'image_id': '00003307_17EE0585_0', 'view': 'Transverse'}]

Patient ID: 00003723

Images: [{'image_id': '00003723_CCF3845C_2', 'view': 'Longitudinal'}]

Patient ID: 00001962

Images: [{'image_id': '00001962_034B467C_1', 'view': 'Transverse'}, {'image_id': '00001962_8FFD0F42_0', 'view': 'Longitudinal'}]

Patient ID: 00002300

Images: [{'image_id': '00002300_E60B804B_0', 'view': 'Transverse'}]

Patient ID: 00003387

Images: [{'image_id': '00003387_76B10567_2', 'view': 'Transverse'}]

Patient ID: 00001362

Images: [{'image_id': '00001362_5EA700B7_0', 'view': 'Transverse'}]

Patient ID: 00002722

Images: [{'image_id': '00002722_0B61FD23_2', 'view': 'Longitudinal'}]

Patient ID: 00000353

Images: [{'image_id': '00000353_883F0C38_0', 'view': 'Longitudinal'}]

Patient ID: 00003891

Images: [{'image_id': '00003891_D1D14835_4', 'view': 'Unknown'}]

Patient ID: 00004035

Images: [{'image_id': '00004035_67EE1254_1', 'view': 'Transverse'}]

Patient ID: 00000689

Images: [{'image_id': '00000689_5DDC80B8_1', 'view': 'Transverse'}]

Patient ID: 00000244

Images: [{'image_id': '00000244_B8CF86FD_0', 'view': 'Longitudinal'}]

Patient ID: 00003035

Images: [{'image_id': '00003035_B50CCC3A_2', 'view': 'Transverse'}]

Patient ID: 00000299

Images: [{'image_id': '00000299_9987EB8C_0', 'view': 'Longitudinal'}]

Patient ID: 00003118

Images: [{'image_id': '00003118_109FF640_3', 'view': 'Transverse'}]

Patient ID: 00003495

Images: [{'image_id': '00003495_9FD9BD0B_1', 'view': 'Longitudinal'}]

Patient ID: 00002706

Images: [{'image_id': '00002706_EFC889ED_0', 'view': 'Transverse'}]

Patient ID: 00000498

Images: [{'image_id': '00000498_CA1667E9_3', 'view': 'Transverse'}]

Patient ID: 00000676

Images: [{'image_id': '00000676_3AF33F07_2', 'view': 'Transverse'}]

Patient ID: 00003496

Images: [{'image_id': '00003496_52E2F6E5_0', 'view': 'Longitudinal'}]

Patient ID: 00000712

Images: [{'image_id': '00000712_F5B42CFA_0', 'view': 'Longitudinal'}]

Patient ID: 00003869

Images: [{'image_id': '00003869_C35ED365_3', 'view': 'Longitudinal'}]

Patient ID: 00000320

Images: [{'image_id': '00000320_AC171F00_1', 'view': 'Unknown'}]

Patient ID: 00003348

Images: [{'image_id': '00003348_C01AC6F5_1', 'view': 'Longitudinal'}]

Patient ID: 00002139

Images: [{'image_id': '00002139_F9A97993_0', 'view': 'Transverse'}]

Patient ID: 00002626

Images: [{'image_id': '00002626_C78A7D1B_2', 'view': 'Unknown'}]

Patient ID: 00000141

Images: [{'image_id': '00000141_CFD4B94F_0', 'view': 'Transverse'}]

Patient ID: 00002897

Images: [{'image_id': '00002897_3E95E8F3_1', 'view': 'Transverse'}]

Patient ID: 00002008

Images: [{'image_id': '00002008_8AC4100D_0', 'view': 'Transverse'}]

Patient ID: 00002759

Images: [{'image_id': '00002759_67AB9CA9_3', 'view': 'Longitudinal'}, {'image_id': '00002759_8CE6E95E_2', 'view': 'Transverse'}]

Patient ID: 00001172

Images: [{'image_id': '00001172_34E4745B_1', 'view': 'Transverse'}]

Patient ID: 00002329

Images: [{'image_id': '00002329_12692A34_0', 'view': 'Longitudinal'}]

Patient ID: 00001531

Images: [{'image_id': '00001531_6C6E8F29_0', 'view': 'Longitudinal'}]

Patient ID: 00003422

Images: [{'image_id': '00003422_41791C2E_2', 'view': 'Transverse'}]

Patient ID: 00003992

Images: [{'image_id': '00003992_E19E84B3_1', 'view': 'Longitudinal'}]

Patient ID: 00002980

Images: [{'image_id': '00002980_5A1D52F5_3', 'view': 'Transverse'}]

Patient ID: 00002564

Images: [{'image_id': '00002564_091C8F17_1', 'view': 'Transverse'}, {'image_id': '00002564_074B4873_2', 'view': 'Unknown'}]

Patient ID: 00003648

Images: [{'image_id': '00003648_64088A99_0', 'view': 'Longitudinal'}, {'image_id': '00003648_EE87CC6D_1', 'view': 'Transverse'}]

Patient ID: 00003108

Images: [{'image_id': '00003108_DD20CD2D_3', 'view': 'Unknown'}, {'image_id': '00003108_AE5AD07C_1', 'view': 'Transverse'}]

Patient ID: 00001071

Images: [{'image_id': '00001071_B2AA850F_0', 'view': 'Transverse'}, {'image_id': '00001071_78AAA4D7_1', 'view': 'Longitudinal'}]

Patient ID: 00001798

Images: [{'image_id': '00001798_77CFF927_1', 'view': 'Transverse'}, {'image_id': '00001798_0129C07F_2', 'view': 'Longitudinal'}]

Patient ID: 00000239

Images: [{'image_id': '00000239_C2174724_1', 'view': 'Transverse'}]

Patient ID: 00004739

Images: [{'image_id': '00004739_7A5FDE47_1', 'view': 'Transverse'}]

Patient ID: 00003302

Images: [{'image_id': '00003302_980F1918_3', 'view': 'Longitudinal'}]

Patient ID: 00004556

Images: [{'image_id': '00004556_B4A47A0E_0', 'view': 'Transverse'}]

Patient ID: 00003755

Images: [{'image_id': '00003755_E4FB4AE4_0', 'view': 'Transverse'}]

Patient ID: 00001151

Images: [{'image_id': '00001151_FC0722AE_1', 'view': 'Longitudinal'}, {'image_id': '00001151_21D3CDCF_2', 'view': 'Unknown'}]

Patient ID: 00003712

Images: [{'image_id': '00003712_3B60994C_4', 'view': 'Longitudinal'}, {'image_id': '00003712_DAB6E827_5', 'view': 'Unknown'}, {'image_id': '00003712_755843D3_2', 'view': 'Transverse'}]

Patient ID: 00002317

Images: [{'image_id': '00002317_7B3E6772_0', 'view': 'Transverse'}]

Patient ID: 00001446

Images: [{'image_id': '00001446_E2085904_0', 'view': 'Transverse'}]

Patient ID: 00000333

Images: [{'image_id': '00000333_428B7BD7_0', 'view': 'Transverse'}, {'image_id': '00000333_6549FB43_2', 'view': 'Longitudinal'}]

Patient ID: 00004582

Images: [{'image_id': '00004582_A326F9AB_2', 'view': 'Longitudinal'}]

Patient ID: 00002782

Images: [{'image_id': '00002782_11E2978D_0', 'view': 'Transverse'}]

Patient ID: 00000705

Images: [{'image_id': '00000705_A5A99D8A_2', 'view': 'Longitudinal'}]

Patient ID: 00000724

Images: [{'image_id': '00000724_FBC8E7E2_1', 'view': 'Transverse'}, {'image_id': '00000724_0F03EA4C_2', 'view': 'Unknown'}]

Patient ID: 00002376

Images: [{'image_id': '00002376_F529823F_3', 'view': 'Transverse'}]

Patient ID: 00003033

Images: [{'image_id': '00003033_6005A5A6_1', 'view': 'Longitudinal'}, {'image_id': '00003033_AEE9D703_3', 'view': 'Transverse'}]

Patient ID: 00000788

Images: [{'image_id': '00000788_8E42B3C9_1', 'view': 'Longitudinal'}]

Patient ID: 00001225

Images: [{'image_id': '00001225_EF55F128_4', 'view': 'Transverse'}]

Patient ID: 00004021

Images: [{'image_id': '00004021_F8E204D0_0', 'view': 'Transverse'}]

Patient ID: 00003304

Images: [{'image_id': '00003304_9453FFA5_2', 'view': 'Transverse'}, {'image_id': '00003304_00990C42_1', 'view': 'Transverse'}]

Patient ID: 00003730

Images: [{'image_id': '00003730_489C1FC9_3', 'view': 'Unknown'}, {'image_id': '00003730_429CBA29_5', 'view': 'Longitudinal'}]

Patient ID: 00001907

Images: [{'image_id': '00001907_D695209F_0', 'view': 'Longitudinal'}]

Patient ID: 00002678

Images: [{'image_id': '00002678_37E14302_1', 'view': 'Transverse'}, {'image_id': '00002678_7A69C716_3', 'view': 'Unknown'}]

Patient ID: 00000631

Images: [{'image_id': '00000631_4B36FAA9_1', 'view': 'Longitudinal'}]

Patient ID: 00001620

Images: [{'image_id': '00001620_61BED965_1', 'view': 'Transverse'}]

Patient ID: 00003494

Images: [{'image_id': '00003494_999DB6DA_1', 'view': 'Transverse'}]

Patient ID: 00004278

Images: [{'image_id': '00004278_53FECB07_2', 'view': 'Unknown'}]

Patient ID: 00000460

Images: [{'image_id': '00000460_C8B2D1A0_4', 'view': 'Longitudinal'}]

Patient ID: 00004607

Images: [{'image_id': '00004607_BD4D2BF0_0', 'view': 'Unknown'}, {'image_id': '00004607_016EE2DD_2', 'view': 'Unknown'}]

Patient ID: 00000496

Images: [{'image_id': '00000496_9E7B6770_3', 'view': 'Unknown'}]

Patient ID: 00002100

Images: [{'image_id': '00002100_C37DE743_0', 'view': 'Longitudinal'}]

Patient ID: 00002613

Images: [{'image_id': '00002613_673E3FC4_2', 'view': 'Longitudinal'}, {'image_id': '00002613_E9A907BE_0', 'view': 'Longitudinal'}]

Patient ID: 00000583

Images: [{'image_id': '00000583_45139B88_2', 'view': 'Longitudinal'}]

Patient ID: 00003110

Images: [{'image_id': '00003110_170514ED_2', 'view': 'Transverse'}, {'image_id': '00003110_E741AC77_5', 'view': 'Longitudinal'}, {'image_id': '00003110_15944615_1', 'view': 'Transverse'}, {'image_id': '00003110_ABBD7CBC_0', 'view': 'Unknown'}]

Patient ID: 00002095

Images: [{'image_id': '00002095_8D0CED5D_0', 'view': 'Longitudinal'}]

Patient ID: 00003376

Images: [{'image_id': '00003376_0AA6CAF2_0', 'view': 'Transverse'}]

Patient ID: 00002006

Images: [{'image_id': '00002006_4D52E291_1', 'view': 'Longitudinal'}]

Patient ID: 00004594

Images: [{'image_id': '00004594_9BFE70C2_2', 'view': 'Longitudinal'}, {'image_id': '00004594_DC7CE428_1', 'view': 'Transverse'}]

Patient ID: 00002386

Images: [{'image_id': '00002386_CF8EB892_1', 'view': 'Transverse'}]

Patient ID: 00001429

Images: [{'image_id': '00001429_2EFE0FB3_1', 'view': 'Longitudinal'}]

Patient ID: 00003772

Images: [{'image_id': '00003772_CA14876A_2', 'view': 'Transverse'}]

Patient ID: 00002171

Images: [{'image_id': '00002171_08AE5477_2', 'view': 'Longitudinal'}]

Patient ID: 00001249

Images: [{'image_id': '00001249_004EE4EE_0', 'view': 'Longitudinal'}]

Patient ID: 00001196

Images: [{'image_id': '00001196_C45D51FD_2', 'view': 'Longitudinal'}]

Patient ID: 00003239

Images: [{'image_id': '00003239_91D8199A_0', 'view': 'Longitudinal'}]

Patient ID: 00002857

Images: [{'image_id': '00002857_28EA146D_3', 'view': 'Transverse'}]

Patient ID: 00001989

Images: [{'image_id': '00001989_B4D68A2B_2', 'view': 'Longitudinal'}]

Patient ID: 00001394

Images: [{'image_id': '00001394_1ADDCE41_2', 'view': 'Longitudinal'}]

Patient ID: 00000852

Images: [{'image_id': '00000852_E9846CBF_1', 'view': 'Transverse'}]

Patient ID: 00003666

Images: [{'image_id': '00003666_1DE085E0_1', 'view': 'Longitudinal'}]

Patient ID: 00002805

Images: [{'image_id': '00002805_C5961CCC_2', 'view': 'Transverse'}, {'image_id': '00002805_72CE45D0_0', 'view': 'Unknown'}]

Patient ID: 00000495

Images: [{'image_id': '00000495_52AA3323_3', 'view': 'Longitudinal'}]

Patient ID: 00003428

Images: [{'image_id': '00003428_05CEF222_0', 'view': 'Transverse'}, {'image_id': '00003428_6B106764_2', 'view': 'Transverse'}]

Patient ID: 00002702

Images: [{'image_id': '00002702_D4C32BC9_0', 'view': 'Longitudinal'}]

Patient ID: 00003521

Images: [{'image_id': '00003521_A3069EEF_1', 'view': 'Transverse'}]

Patient ID: 00001053

Images: [{'image_id': '00001053_4E15B104_3', 'view': 'Transverse'}]

Patient ID: 00003816

Images: [{'image_id': '00003816_81ADAF2E_1', 'view': 'Longitudinal'}]

Patient ID: 00004058

Images: [{'image_id': '00004058_01CCEBC6_9', 'view': 'Longitudinal'}]

Patient ID: 00003567

Images: [{'image_id': '00003567_508FEF53_1', 'view': 'Transverse'}]

Patient ID: 00000345

Images: [{'image_id': '00000345_7C72D738_0', 'view': 'Longitudinal'}]

Patient ID: 00001870

Images: [{'image_id': '00001870_8B0633C9_1', 'view': 'Longitudinal'}]

Patient ID: 00003251

Images: [{'image_id': '00003251_586CE88F_3', 'view': 'Transverse'}]

Patient ID: 00004678

Images: [{'image_id': '00004678_CC18E23B_0', 'view': 'Transverse'}, {'image_id': '00004678_9BE4AE69_2', 'view': 'Unknown'}]

Patient ID: 00003292

Images: [{'image_id': '00003292_B5C3176F_2', 'view': 'Longitudinal'}]

Patient ID: 00003873

Images: [{'image_id': '00003873_1522E24A_2', 'view': 'Longitudinal'}]

Patient ID: 00004015

Images: [{'image_id': '00004015_12245EE4_0', 'view': 'Transverse'}]

Patient ID: 00003036

Images: [{'image_id': '00003036_22FC7644_2', 'view': 'Transverse'}, {'image_id': '00003036_EA94EA4C_0', 'view': 'Transverse'}]

Patient ID: 00002924

Images: [{'image_id': '00002924_95D913E7_1', 'view': 'Transverse'}]

Patient ID: 00004680

Images: [{'image_id': '00004680_FC71DCBB_3', 'view': 'Transverse'}]

Patient ID: 00003743

Images: [{'image_id': '00003743_2235ECB8_0', 'view': 'Transverse'}]

Patient ID: 00001205

Images: [{'image_id': '00001205_B202DECD_1', 'view': 'Transverse'}]

Patient ID: 00004009

Images: [{'image_id': '00004009_7AB5E6CF_1', 'view': 'Transverse'}]

Patient ID: 00002241

Images: [{'image_id': '00002241_DDC56ABB_0', 'view': 'Longitudinal'}, {'image_id': '00002241_71CC4367_2', 'view': 'Longitudinal'}]

Patient ID: 00000578

Images: [{'image_id': '00000578_81A1AAD4_3', 'view': 'Unknown'}, {'image_id': '00000578_AAD6BA89_1', 'view': 'Unknown'}]

Patient ID: 00000968

Images: [{'image_id': '00000968_9926DE87_1', 'view': 'Longitudinal'}, {'image_id': '00000968_B8DF7DC6_0', 'view': 'Transverse'}]

Patient ID: 00003471

Images: [{'image_id': '00003471_CB3A5690_0', 'view': 'Transverse'}]

Patient ID: 00001343

Images: [{'image_id': '00001343_E4E2D9FA_0', 'view': 'Transverse'}]

Patient ID: 00001321

Images: [{'image_id': '00001321_5D10EC11_0', 'view': 'Transverse'}]

Patient ID: 00002147

Images: [{'image_id': '00002147_97733F34_1', 'view': 'Transverse'}]

Patient ID: 00003846

Images: [{'image_id': '00003846_9B615DC6_3', 'view': 'Transverse'}]

Patient ID: 00003037

Images: [{'image_id': '00003037_084EB684_4', 'view': 'Longitudinal'}, {'image_id': '00003037_03F931F6_0', 'view': 'Transverse'}]

Patient ID: 00004056

Images: [{'image_id': '00004056_E129D4B4_6', 'view': 'Longitudinal'}]

Patient ID: 00003961

Images: [{'image_id': '00003961_E74DF424_0', 'view': 'Transverse'}]

Patient ID: 00003339

Images: [{'image_id': '00003339_2E1B6AA4_1', 'view': 'Longitudinal'}]

Patient ID: 00001533

Images: [{'image_id': '00001533_B6B4E396_1', 'view': 'Transverse'}]

Patient ID: 00004756

Images: [{'image_id': '00004756_537CCD1B_2', 'view': 'Unknown'}]

Patient ID: 00000773

Images: [{'image_id': '00000773_AC9FAB14_0', 'view': 'Longitudinal'}]

Patient ID: 00001452

Images: [{'image_id': '00001452_F32D3C02_0', 'view': 'Unknown'}]

Patient ID: 00004711

Images: [{'image_id': '00004711_680C20B8_1', 'view': 'Transverse'}]

Patient ID: 00004584

Images: [{'image_id': '00004584_CD17F323_1', 'view': 'Longitudinal'}]

Patient ID: 00003331

Images: [{'image_id': '00003331_F25E0CE3_0', 'view': 'Longitudinal'}]

Patient ID: 00000261

Images: [{'image_id': '00000261_A5969F13_3', 'view': 'Longitudinal'}, {'image_id': '00000261_D6C54E9E_0', 'view': 'Longitudinal'}]

Patient ID: 00002788

Images: [{'image_id': '00002788_FCF8AC51_1', 'view': 'Longitudinal'}]

Patient ID: 00002434

Images: [{'image_id': '00002434_4CF40A72_1', 'view': 'Longitudinal'}]

Patient ID: 00000875

Images: [{'image_id': '00000875_8FB50796_0', 'view': 'Longitudinal'}]

Patient ID: 00003135

Images: [{'image_id': '00003135_80CF98B5_2', 'view': 'Transverse'}]

Patient ID: 00002768

Images: [{'image_id': '00002768_657319E5_0', 'view': 'Transverse'}]

Patient ID: 00001666

Images: [{'image_id': '00001666_20BDD798_1', 'view': 'Longitudinal'}]

Patient ID: 00000870

Images: [{'image_id': '00000870_BCD3F9C8_0', 'view': 'Longitudinal'}]

Patient ID: 00002638

Images: [{'image_id': '00002638_BA1F0377_0', 'view': 'Transverse'}]

Patient ID: 00002480

Images: [{'image_id': '00002480_AC7C4D6D_1', 'view': 'Longitudinal'}]

Patient ID: 00004031

Images: [{'image_id': '00004031_84075C6C_0', 'view': 'Unknown'}]

Patient ID: 00003091

Images: [{'image_id': '00003091_666CFE4C_2', 'view': 'Transverse'}]

Patient ID: 00001803

Images: [{'image_id': '00001803_6379CB70_0', 'view': 'Transverse'}]

Patient ID: 00000577

Images: [{'image_id': '00000577_CF656C90_0', 'view': 'Longitudinal'}]

Patient ID: 00003913

Images: [{'image_id': '00003913_1289FC75_0', 'view': 'Longitudinal'}]

Patient ID: 00002749

Images: [{'image_id': '00002749_1784B49C_1', 'view': 'Transverse'}]

Patient ID: 00003868

Images: [{'image_id': '00003868_B2DFC15A_1', 'view': 'Transverse'}]

Patient ID: 00004038

Images: [{'image_id': '00004038_E562B24C_0', 'view': 'Transverse'}]

Patient ID: 00002251

Images: [{'image_id': '00002251_7CA21CDC_1', 'view': 'Longitudinal'}]

Patient ID: 00000139

Images: [{'image_id': '00000139_FA7E0544_0', 'view': 'Longitudinal'}, {'image_id': '00000139_217557BB_1', 'view': 'Unknown'}]

Patient ID: 00001905

Images: [{'image_id': '00001905_FE15239B_0', 'view': 'Transverse'}]

Patient ID: 00000713

Images: [{'image_id': '00000713_D6CDBB67_1', 'view': 'Unknown'}]

Patient ID: 00003024

Images: [{'image_id': '00003024_FAC23E95_1', 'view': 'Unknown'}]

Patient ID: 00003566

Images: [{'image_id': '00003566_E5E9B40A_0', 'view': 'Transverse'}]

Patient ID: 00003748

Images: [{'image_id': '00003748_16F432E0_1', 'view': 'Transverse'}]

Patient ID: 00001043

Images: [{'image_id': '00001043_53DDFED0_1', 'view': 'Longitudinal'}]

Patient ID: 00003587

Images: [{'image_id': '00003587_7E59F0F0_1', 'view': 'Longitudinal'}]

Patient ID: 00001540

Images: [{'image_id': '00001540_A85A7F7A_0', 'view': 'Transverse'}]

Patient ID: 00001657

Images: [{'image_id': '00001657_2EBD661C_0', 'view': 'Longitudinal'}]

Patient ID: 00001931

Images: [{'image_id': '00001931_D0BF5320_1', 'view': 'Transverse'}]

Patient ID: 00000984

Images: [{'image_id': '00000984_6A14FD3A_0', 'view': 'Longitudinal'}]

Patient ID: 00001827

Images: [{'image_id': '00001827_249CFE15_1', 'view': 'Longitudinal'}]

Patient ID: 00002552

Images: [{'image_id': '00002552_1B25A5FC_1', 'view': 'Unknown'}]

Patient ID: 00002604

Images: [{'image_id': '00002604_DB762E8A_0', 'view': 'Longitudinal'}]

Patient ID: 00000152

Images: [{'image_id': '00000152_FED1C9E5_2', 'view': 'Transverse'}]

Patient ID: 00002908

Images: [{'image_id': '00002908_A6E0BBFF_0', 'view': 'Longitudinal'}]

Patient ID: 00001388

Images: [{'image_id': '00001388_E9B6B324_1', 'view': 'Longitudinal'}]

Patient ID: 00000440

Images: [{'image_id': '00000440_5DC20C46_2', 'view': 'Unknown'}]

Patient ID: 00003433

Images: [{'image_id': '00003433_CF6255AE_0', 'view': 'Longitudinal'}]

Patient ID: 00000298

Images: [{'image_id': '00000298_233B954B_2', 'view': 'Longitudinal'}]

Patient ID: 00003678

Images: [{'image_id': '00003678_6B9ECDA5_0', 'view': 'Transverse'}]

Patient ID: 00003358

Images: [{'image_id': '00003358_EED38051_3', 'view': 'Unknown'}]

Patient ID: 00002607

Images: [{'image_id': '00002607_1644E7FB_2', 'view': 'Longitudinal'}]

Patient ID: 00001996

Images: [{'image_id': '00001996_3F0DCAF8_1', 'view': 'Unknown'}, {'image_id': '00001996_E78BF804_2', 'view': 'Longitudinal'}]

Patient ID: 00004034

Images: [{'image_id': '00004034_B089D9A9_0', 'view': 'Longitudinal'}, {'image_id': '00004034_86881609_2', 'view': 'Longitudinal'}]

Patient ID: 00001956

Images: [{'image_id': '00001956_027E3C07_2', 'view': 'Transverse'}]

Patient ID: 00002524

Images: [{'image_id': '00002524_8EA7E99F_3', 'view': 'Longitudinal'}]

Patient ID: 00001722

Images: [{'image_id': '00001722_67679027_1', 'view': 'Longitudinal'}]

Patient ID: 00002427

Images: [{'image_id': '00002427_DB5052F7_0', 'view': 'Longitudinal'}]

Patient ID: 00001405

Images: [{'image_id': '00001405_324C8819_1', 'view': 'Transverse'}]

Patient ID: 00000242

Images: [{'image_id': '00000242_B2BA5E1E_2', 'view': 'Longitudinal'}]

Patient ID: 00000372

Images: [{'image_id': '00000372_5CF2D6D2_0', 'view': 'Transverse'}, {'image_id': '00000372_2698ED21_1', 'view': 'Longitudinal'}]

Patient ID: 00003520

Images: [{'image_id': '00003520_2DA27C78_1', 'view': 'Transverse'}]

Patient ID: 00003464

Images: [{'image_id': '00003464_BDB7D9B8_0', 'view': 'Longitudinal'}]

Patient ID: 00000741

Images: [{'image_id': '00000741_0A857FFE_0', 'view': 'Longitudinal'}]

Patient ID: 00004004

Images: [{'image_id': '00004004_9D7F93FD_0', 'view': 'Longitudinal'}]

Patient ID: 00002019

Images: [{'image_id': '00002019_8FCF2FC5_1', 'view': 'Longitudinal'}]

Patient ID: 00000146

Images: [{'image_id': '00000146_8EC61D31_1', 'view': 'Transverse'}]

Patient ID: 00002933

Images: [{'image_id': '00002933_98634EA1_3', 'view': 'Unknown'}]

Patient ID: 00003150

Images: [{'image_id': '00003150_4E9B4766_3', 'view': 'Transverse'}]

Patient ID: 00001158

Images: [{'image_id': '00001158_A701E538_2', 'view': 'Longitudinal'}]

Patient ID: 00001628

Images: [{'image_id': '00001628_BDDF3EB3_1', 'view': 'Longitudinal'}]

Patient ID: 00001788

Images: [{'image_id': '00001788_BC9757C5_2', 'view': 'Longitudinal'}]

Patient ID: 00003767


In [79]:
def thyroidxl_preprocess(
    image_path: Path,
    outputsize: C1_SIZE,
    remove_black_edges: bool = True,
):
    """
    ThyroidXL-safe replacement for TNSCUI_preprocess. 
    (original function in utils:
        removes irrelevant edges based on a threshold system of averaged pixels row-wise; the default output_size is 256 x 256
        returns the cut image tensor, coordinates of the min and max x and y FROM ORIGINAL IMAGE respectively that the extracted image without irrelevant
        areas contains  

    Returns
    -------
    processed_tensor:
        Float tensor with shape [output_size, output_size].

    cut_shape:
        Shape of the retained image before resizing.

    original_shape:
        Original image shape: (height, width).

    location:
        Coordinates of the retained image in the original image:
        [row_start, row_end, col_start, col_end].
    """

   
    with Image.open(image_path) as image:
        image = image.convert("L")
        image_array = np.asarray(image, dtype=np.float32)

    original_shape = image_array.shape

    if image_array.ndim != 2:
        raise ValueError(
            f"Expected a 2-D grayscale image, got {image_array.shape} "
            f"for {image_path.name}"
        )

    if remove_black_edges:
        # Detect rows and columns that contain meaningful ultrasound content.
        #
        # A small threshold is used instead of requiring pixels to be exactly
        # zero because ultrasound borders may contain compression noise.
        foreground_threshold = 5.0

        valid_rows = np.where(
            np.mean(image_array, axis=1) > foreground_threshold
        )[0]

        valid_cols = np.where(
            np.mean(image_array, axis=0) > foreground_threshold
        )[0]

        if len(valid_rows) > 0 and len(valid_cols) > 0:
            row_start = int(valid_rows[0])
            row_end = int(valid_rows[-1]) + 1

            col_start = int(valid_cols[0])
            col_end = int(valid_cols[-1]) + 1
        else:
            # Fall back to the complete image if no foreground is found.
            row_start = 0
            row_end = original_shape[0]
            col_start = 0
            col_end = original_shape[1]

    else:
        row_start = 0
        row_end = original_shape[0]
        col_start = 0
        col_end = original_shape[1]

    cropped_image = image_array[
        row_start:row_end,
        col_start:col_end,
    ]

    if cropped_image.size == 0:
        raise ValueError(
            f"Black-edge removal produced an empty image for "
            f"{image_path.name}"
        )

    cut_shape = cropped_image.shape
    location = [row_start, row_end, col_start, col_end]

    # Resize to the stage-1 
    processed_array = resize(
        cropped_image,
        (outputsize, outputsize),
        order=3,
        preserve_range=True,
        anti_aliasing=True,
    ).astype(np.float32)

    # Match the common neural-network image range.
    if processed_array.max() > 1.0:
        processed_array /= 255.0

    processed_tensor = torch.from_numpy(processed_array)

    return processed_tensor, cut_shape, original_shape, location

In [80]:
# Metrics 

def get_iou(prediction: np.ndarray, ground_truth: np.ndarray) -> float:
    """Calculate intersection over union for two binary arrays --> corresponds to ."""
    prediction = prediction.astype(bool)
    ground_truth = ground_truth.astype(bool)

    intersection = np.logical_and(prediction, ground_truth).sum()
    union = np.logical_or(prediction, ground_truth).sum()

    if union == 0:
        return 1.0

    return float(intersection / union)


def get_dsc(prediction: np.ndarray, ground_truth: np.ndarray) -> float:
    """Calculate Dice similarity coefficient for two binary arrays."""
    prediction = prediction.astype(bool)
    ground_truth = ground_truth.astype(bool)

    intersection = np.logical_and(prediction, ground_truth).sum()
    denominator = prediction.sum() + ground_truth.sum()

    if denominator == 0:
        return 1.0

    return float((2.0 * intersection) / denominator)


def largest_connected_component(binary_mask: np.ndarray) -> np.ndarray:
    """Retain only the largest foreground connected component."""
    binary_mask = binary_mask.astype(bool)

    if binary_mask.sum() == 0:
        return binary_mask.astype(np.float32)

    labeled_img, num_components = sklabel(
        binary_mask,
        connectivity=1,
        background=0,
        return_num=True,
    )

    if num_components == 1:
        return binary_mask.astype(np.float32)

    component_sizes = [
        np.sum(labeled_img == component_label)
        for component_label in range(1, num_components + 1)
    ]

    largest_label = int(np.argmax(component_sizes)) + 1
    return (labeled_img == largest_label).astype(np.float32)


def calculate_stage2_roi(
    stage1_mask: np.ndarray,
    c1_size: int = 256,
) -> Tuple[int, int, int, int]:
    """
    Calculate the expanded square ROI used as input to Stage 2.

    Returns
    -------
    row_min, row_max, col_min, col_max
    """
    if stage1_mask.sum() == 0:
        min_row, min_col, max_row, max_col = 0, 0, c1_size, c1_size
    else:
        region = regionprops(stage1_mask.astype(np.uint8))[0]
        min_row, min_col, max_row, max_col = region.bbox

    row_center = (max_row + min_row) // 2
    col_center = (max_col + min_col) // 2
    max_length = max(max_row - min_row, max_col - min_col)

    large_roi_threshold = int((c1_size / 256) * 80)
    large_roi_margin = int((c1_size / 256) * 19)
    small_roi_margin = int((c1_size / 256) * 31)

    if max_length > large_roi_threshold:
        expansion = large_roi_margin + max_length // 2
    else:
        expansion = small_roi_margin + max_length // 2

    row_min = max(0, row_center - expansion)
    row_max = min(c1_size, row_center + expansion)
    col_min = max(0, col_center - expansion)
    col_max = min(c1_size, col_center + expansion)

    # IN case the crop is empty    
    if row_max <= row_min or col_max <= col_min:
        return 0, c1_size, 0, c1_size

    return row_min, row_max, col_min, col_max


# save files in order 

def discover_images(image_dir: Path) -> List[Path]:
    """Return every supported image file recursively, in stable order."""
    files = [
        path
        for path in image_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS
    ]
    return sorted(files, key=lambda path: str(path).lower())


def build_mask_index(mask_dir: Path) -> Dict[str, Path]:
    """
    Index masks by filename stem, case-insensitively.

    The image and mask may have different filename extensions, but their stems
    must match
    """
    index: Dict[str, Path] = {}

    for path in discover_images(mask_dir):
        key = path.stem.lower()

        if key in index:
            raise ValueError(
                f"Duplicate mask stem '{path.stem}' found:\n"
                f"  {index[key]}\n"
                f"  {path}"
            )

        index[key] = path

    return index


def load_binary_mask(mask_path: Path, expected_shape: Tuple[int, int]) -> np.ndarray:
    """Read a mask as grayscale and convert it to a binary NumPy array."""
    mask = Image.open(mask_path).convert("L")
    mask_array = np.asarray(mask, dtype=np.float32)

    if mask_array.shape != expected_shape:
        raise ValueError(
            f"Ground-truth mask shape {mask_array.shape} does not match "
            f"original image shape {expected_shape} for {mask_path.name}."
        )

    return (mask_array > 0).astype(np.float32)


def save_binary_mask(mask: np.ndarray, output_path: Path) -> None:
    """Save a binary mask as an 8-bit PNG."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    mask_uint8 = (mask.astype(bool).astype(np.uint8) * 255)
    Image.fromarray(mask_uint8, mode="L").save(output_path)


def save_overlay(
    image_path: Path,
    prediction: np.ndarray,
    ground_truth: Optional[np.ndarray],
    output_path: Path,
) -> None:
    """
    Save an RGB overlay:
    - red: the prediction
    - green: the ground truth (from given mask)
    - yellow: overlap
    """
    original = Image.open(image_path).convert("L")
    base = np.asarray(original, dtype=np.float32)

    if base.max() > base.min():
        base = (base - base.min()) / (base.max() - base.min())
    else:
        base = np.zeros_like(base)

    rgb = np.stack([base, base, base], axis=-1)
    prediction_bool = prediction.astype(bool)

    rgb[prediction_bool, 0] = 1.0
    rgb[prediction_bool, 1] *= 0.35
    rgb[prediction_bool, 2] *= 0.35

    if ground_truth is not None:
        ground_truth_bool = ground_truth.astype(bool)
        rgb[ground_truth_bool, 1] = 1.0
        rgb[ground_truth_bool, 0] *= 0.35
        rgb[ground_truth_bool, 2] *= 0.35

        overlap = np.logical_and(prediction_bool, ground_truth_bool)
        rgb[overlap, 0] = 1.0
        rgb[overlap, 1] = 1.0
        rgb[overlap, 2] = 0.0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray((np.clip(rgb, 0, 1) * 255).astype(np.uint8), mode="RGB").save(
        output_path
    )


# ============================================================================
# Model loading and inference
# ============================================================================

def choose_device() -> torch.device:
    """Prefer Apple MPS, then CUDA, then CPU."""
    if torch.backends.mps.is_available():
        return torch.device("mps")

    if torch.cuda.is_available():
        return torch.device("cuda")

    return torch.device("cpu")


def extract_state_dict(checkpoint):
    """
    Support either a direct state_dict or a checkpoint dictionary containing
    a state_dict/model_state_dict field.
    """
    if not isinstance(checkpoint, dict):
        return checkpoint

    if "state_dict" in checkpoint:
        return checkpoint["state_dict"]

    if "model_state_dict" in checkpoint:
        return checkpoint["model_state_dict"]

    return checkpoint


def load_model(
    weight_path: Path,
    device: torch.device,
    transforms,
    use_tta: bool,
) -> torch.nn.Module:
    """Create a DeepLabV3+ model and load pretrained weights."""
    if not weight_path.exists():
        raise FileNotFoundError(f"Weight file not found: {weight_path}")

    model = smp.DeepLabV3Plus(
        encoder_name="efficientnet-b6",
        encoder_weights=None,
        in_channels=1,
        classes=1,
    )

    # CPU deserialization is typically the safest for old checkpoints.
    checkpoint = torch.load(weight_path, map_location="cpu")
    state_dict = extract_state_dict(checkpoint)

    try:
        model.load_state_dict(state_dict, strict=True)
    except RuntimeError as exc:
        print(
            f"Strict loading failed for {weight_path.name}; "
            "retrying with strict=False."
        )
        print(exc)
        incompatible = model.load_state_dict(state_dict, strict=False)
        print("Missing keys:", incompatible.missing_keys)
        print("Unexpected keys:", incompatible.unexpected_keys)

    model = model.to(device)
    model.eval()

    if use_tta:
        model = tta.SegmentationTTAWrapper(
            model,
            transforms,
            merge_mode="mean",
        )
        model.eval()

    return model


def run_single_image(
    image_path: Path,
    model_cascade1: torch.nn.Module,
    model_cascade2: torch.nn.Module,
    device: torch.device,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Run both cascades on one image.

    Returns
    -------
    final_mask:
        Binary mask restored to the original image dimensions.
    stage1_mask:
        Binary 256x256 Stage-1 largest-component mask.
    """
    processed_img, cut_shape, original_shape, location = thyroidxl_preprocess(
    image_path,
    outputsize=C1_SIZE,
    remove_black_edges=not ORIMG,
    )
    # Convert to a tensor if preprocessing returned a NumPy array.
    if processed_img.ndim != 2:
        raise ValueError(
            f"Expected processed image shape [H, W], got "
            f"{tuple(processed_img.shape)} for {image_path.name}"
        )

    image_tensor = processed_img.unsqueeze(0).unsqueeze(0)
    image_tensor = image_tensor.to(
        device=device,
        dtype=torch.float32,
    )

    assert image_tensor.shape == (1, 1, C1_SIZE, C1_SIZE), (
        f"Incorrect Stage-1 input shape: {tuple(image_tensor.shape)}"
    )

    image_array_256 = processed_img.cpu().numpy()

    with torch.inference_mode():
        stage1_logits = model_cascade1(image_tensor)
        stage1_probability = torch.sigmoid(stage1_logits)

    stage1_mask = (
        stage1_probability.squeeze().detach().cpu().numpy() > C1_THRESHOLD
    ).astype(np.float32)

    stage1_mask = largest_connected_component(stage1_mask)

    working_mask_256 = stage1_mask.copy()

    if USE_C2:
        row_min, row_max, col_min, col_max = calculate_stage2_roi(
            stage1_mask,
            C1_SIZE,
        )

        roi = image_array_256[row_min:row_max, col_min:col_max]
        roi_original_shape = roi.shape

        if roi.size == 0:
            raise RuntimeError(
                f"Stage-2 ROI is empty for {image_path.name}: "
                f"{(row_min, row_max, col_min, col_max)}"
            )

        roi_512 = resize(
            roi,
            (C2_SIZE, C2_SIZE),
            order=3,
            preserve_range=True,
            anti_aliasing=True,
        ).astype(np.float32)

        roi_tensor = torch.from_numpy(roi_512).unsqueeze(0).unsqueeze(0)
        roi_tensor = roi_tensor.to(device=device, dtype=torch.float32)

        with torch.inference_mode():
            stage2_logits = model_cascade2(roi_tensor)
            stage2_probability = torch.sigmoid(stage2_logits)

        stage2_mask_512 = (
            stage2_probability.squeeze().detach().cpu().numpy() > C2_THRESHOLD
        ).astype(np.float32)

        stage2_mask_roi = resize(
            stage2_mask_512,
            roi_original_shape,
            order=C2_RESIZE_ORDER,
            preserve_range=True,
            anti_aliasing=False,
        )

        stage2_mask_roi = (stage2_mask_roi > 0.5).astype(np.float32)

        # Use a blank canvas so the final 256x256 prediction contains only
        # the refined Stage-2 output, rather than leftover Stage-1 pixels.
        working_mask_256 = np.zeros((C1_SIZE, C1_SIZE), dtype=np.float32)
        working_mask_256[row_min:row_max, col_min:col_max] = stage2_mask_roi

    # Reverse the resize performed by TNSCUI_preprocess.
    restored_cut_mask = resize(
        working_mask_256,
        tuple(int(value) for value in cut_shape),
        order=0,
        preserve_range=True,
        anti_aliasing=False,
    )

    restored_cut_mask = (restored_cut_mask > 0.5).astype(np.float32)

    original_shape = tuple(int(value) for value in original_shape)
    final_mask = np.zeros(original_shape, dtype=np.float32)

    row_start, row_end, col_start, col_end = [int(value) for value in location]
    target_shape = (row_end - row_start, col_end - col_start)

    if restored_cut_mask.shape != target_shape:
        restored_cut_mask = resize(
            restored_cut_mask,
            target_shape,
            order=0,
            preserve_range=True,
            anti_aliasing=False,
        )
        restored_cut_mask = (restored_cut_mask > 0.5).astype(np.float32)

    final_mask[row_start:row_end, col_start:col_end] = restored_cut_mask
    final_mask = (final_mask > 0.5).astype(np.float32)

    return final_mask, stage1_mask

In [ ]:
def main() -> None:

    for required_path in (
        IMG_DIR,
        MASK_DIR,
    ):

        if not required_path.exists():

            raise FileNotFoundError(
                f"Directory not found: "
                f"{required_path}"
            )

    if not SCREENED_TXT.exists():

        raise FileNotFoundError(
            f"Screened file not found: "
            f"{SCREENED_TXT}"
        )


    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    PREDICTION_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    if SAVE_OVERLAYS:

        OVERLAY_DIR.mkdir(
            parents=True,
            exist_ok=True,
        )

        PATIENT_COMPARISON_DIR.mkdir(
            parents=True,
            exist_ok=True,
        )


    # Device


    device = choose_device()

    print(
        f"Using device: {device}"
    )

 
    # Load SCREENED patients


    patients = load_screened_patients(
        SCREENED_TXT
    )

    print(
        f"Screened patients: "
        f"{len(patients)}"
    )

    total_screened_images = sum(
        len(images)
        for images
        in patients.values()
    )

    print(
        f"Screened images: "
        f"{total_screened_images}"
    )


    # Build image + mask indexes


    image_index_map = build_image_index(
        IMG_DIR
    )

    mask_index = build_mask_index(
        MASK_DIR
    )

    print(
        f"Raw images indexed: "
        f"{len(image_index_map)}"
    )

    print(
        f"Masks indexed: "
        f"{len(mask_index)}"
    )


    # TTA


    tta_transforms = tta.Compose(
        [
            tta.VerticalFlip(),
            tta.HorizontalFlip(),
            tta.Rotate90(
                angles=[
                    0,
                    180,
                ]
            ),
        ]
    )

    # ==========================================================    # Models


    print(
        "Loading Stage-1 model..."
    )

    model_cascade1 = load_model(
        WEIGHT_C1,
        device,
        tta_transforms,
        C1_TTA,
    )

    print(
        "Loading Stage-2 model..."
    )

    model_cascade2 = load_model(
        WEIGHT_C2,
        device,
        tta_transforms,
        C2_TTA,
    )


    # Results

    results: List[Dict] = []

    failed_count = 0

    # ==========================================================
    # OUTER LOOP = PATIENT
    # ==========================================================

    for patient_number, (
        patient_id,
        patient_images,
    ) in enumerate(
        sorted(patients.items()),
        start=1,
    ):

        print(
            "\n"
            + "=" * 72
        )

        print(
            f"PATIENT "
            f"[{patient_number}/"
            f"{len(patients)}] "
            f"{patient_id}"
        )

        print(
            f"Screened images: "
            f"{len(patient_images)}"
        )

        print(
            "=" * 72
        )

        patient_results = []


        # INNER LOOP = images/views belonging to patient
       
        for image_number, image_info in enumerate(
            patient_images,
            start=1,
        ):

            image_id = (
                image_info[
                    "image_id"
                ]
                .strip()
            )

            view = (
                image_info[
                    "view"
                ]
                .strip()
            )

            image_key = (
                image_id.lower()
            )

            print(
                f"\n  "
                f"[{image_number}/"
                f"{len(patient_images)}] "
                f"{image_id}"
            )

            print(
                f"  View: {view}"
            )

            # --------------------------------------------------
            # Find image
            # --------------------------------------------------

            if (
                image_key
                not in image_index_map
            ):

                print(
                    "  ERROR: image not found."
                )

                failed_count += 1

                result = {
                    "patient_id":
                        patient_id,

                    "image_id":
                        image_id,

                    "view":
                        view,

                    "image_name":
                        "",

                    "image_path":
                        "",

                    "mask_path":
                        "",

                    "prediction_path":
                        "",

                    "overlay_path":
                        "",

                    "height":
                        "",

                    "width":
                        "",

                    "stage1_foreground_pixels":
                        "",

                    "final_foreground_pixels":
                        "",

                    "ground_truth_foreground_pixels":
                        "",

                    "iou":
                        "",

                    "dsc":
                        "",

                    "iou_below_0_3":
                        "",

                    "status":
                        "failed",

                    "error":
                        "Image not found",
                }

                results.append(result)
                patient_results.append(
                    result
                )

                continue

            image_path = (
                image_index_map[
                    image_key
                ]
            )

            # --------------------------------------------------
            # Find the mask of the image 
     

            if image_key not in mask_index:

                print(
                    "  ERROR: mask not found."
                )

                failed_count += 1

                result = {
                    "patient_id":
                        patient_id,

                    "image_id":
                        image_id,

                    "view":
                        view,

                    "image_name":
                        image_path.name,

                    "image_path":
                        str(image_path),

                    "mask_path":
                        "",

                    "prediction_path":
                        "",

                    "overlay_path":
                        "",

                    "height":
                        "",

                    "width":
                        "",

                    "stage1_foreground_pixels":
                        "",

                    "final_foreground_pixels":
                        "",

                    "ground_truth_foreground_pixels":
                        "",

                    "iou":
                        "",

                    "dsc":
                        "",

                    "iou_below_0_3":
                        "",

                    "status":
                        "failed",

                    "error":
                        "Mask not found",
                }

                results.append(result)
                patient_results.append(
                    result
                )

                continue

            mask_path = (
                mask_index[
                    image_key
                ]
            )

            try:

                # Original dimensions


                with Image.open(
                    image_path
                ) as original_image:

                    original_shape = (
                        original_image.height,
                        original_image.width,
                    )

                # Ground truth
  

                ground_truth = (
                    load_binary_mask(
                        mask_path,
                        original_shape,
                    )
                )

                # ==============================================
                # Full TNSCUI inference
                #
                # thyroidxl_preprocess() is called INSIDE
                # run_single_image().
                # ==============================================

                final_mask, stage1_mask = (
                    run_single_image(
                        image_path,
                        model_cascade1,
                        model_cascade2,
                        device,
                    )
                )

                if (
                    final_mask.shape
                    != ground_truth.shape
                ):

                    raise ValueError(
                        f"Prediction shape "
                        f"{final_mask.shape} "
                        "does not match "
                        f"GT shape "
                        f"{ground_truth.shape}"
                    )

                # ==============================================
                # Metrics
                # ==============================================

                iou = get_iou(
                    final_mask,
                    ground_truth,
                )

                dsc = get_dsc(
                    final_mask,
                    ground_truth,
                )

                print(
                    f"  IoU: {iou:.4f}"
                )

                print(
                    f"  DSC: {dsc:.4f}"
                )

                # ==============================================
                # Prediction
                # ==============================================

                prediction_path = (
                    PREDICTION_DIR
                    / f"{image_id}.png"
                )

                save_binary_mask(
                    final_mask,
                    prediction_path,
                )

                # ==============================================
                # Overlay
                # ==============================================

                if SAVE_OVERLAYS:

                    patient_overlay_dir = (
                        OVERLAY_DIR
                        / patient_id
                    )

                    overlay_path = (
                        patient_overlay_dir
                        / (
                            f"{image_id}_"
                            f"{view}_overlay.png"
                        )
                    )

                    save_overlay(
                        image_path,
                        final_mask,
                        ground_truth,
                        overlay_path,
                    )

                else:

                    overlay_path = None

                # ==============================================
                # Result row
                # ==============================================

                result = {
                    "patient_id":
                        patient_id,

                    "image_id":
                        image_id,

                    "view":
                        view,

                    "image_name":
                        image_path.name,

                    "image_path":
                        str(image_path),

                    "mask_path":
                        str(mask_path),

                    "prediction_path":
                        str(
                            prediction_path
                        ),

                    "overlay_path":
                        (
                            str(overlay_path)
                            if overlay_path
                            else ""
                        ),

                    "height":
                        original_shape[0],

                    "width":
                        original_shape[1],

                    "stage1_foreground_pixels":
                        int(
                            stage1_mask.sum()
                        ),

                    "final_foreground_pixels":
                        int(
                            final_mask.sum()
                        ),

                    "ground_truth_foreground_pixels":
                        int(
                            ground_truth.sum()
                        ),

                    "iou":
                        iou,

                    "dsc":
                        dsc,

                    "iou_below_0_3":
                        int(
                            iou < 0.3
                        ),

                    "status":
                        "ok",

                    "error":
                        "",
                }

                results.append(result)

                patient_results.append(
                    result
                )

            except Exception as exc:

                failed_count += 1

                print(
                    f"ERROR processing "
                    f"{image_id}: {exc}"
                )

                traceback.print_exc()

                result = {
                    "patient_id":
                        patient_id,

                    "image_id":
                        image_id,

                    "view":
                        view,

                    "image_name":
                        image_path.name,

                    "image_path":
                        str(image_path),

                    "mask_path":
                        str(mask_path),

                    "prediction_path":
                        "",

                    "overlay_path":
                        "",

                    "height":
                        "",

                    "width":
                        "",

                    "stage1_foreground_pixels":
                        "",

                    "final_foreground_pixels":
                        "",

                    "ground_truth_foreground_pixels":
                        "",

                    "iou":
                        "",

                    "dsc":
                        "",

                    "iou_below_0_3":
                        "",

                    "status":
                        "failed",

                    "error":
                        str(exc),
                }

                results.append(result)

                patient_results.append(
                    result
                )

                if not CONTINUE_ON_ERROR:
                    raise


        # Patient finished
     

        successful_patient_results = [
            row
            for row in patient_results
            if row["status"] == "ok"
        ]

        # ------------------------------------------------------
        # Side-by-side overlay
        # ------------------------------------------------------

        if (
            SAVE_OVERLAYS
            and len(
                successful_patient_results
            ) >= 2
        ):

            comparison_path = (
                PATIENT_COMPARISON_DIR
                / (
                    f"{patient_id}"
                    f"_comparison.png"
                )
            )

            save_patient_comparison(
                patient_id,
                successful_patient_results,
                comparison_path,
            )

            print(
                f"\n  Comparison saved:"
                f"\n  {comparison_path}"
            )


        # Patient running metrics


        if successful_patient_results:

            patient_ious = np.asarray(
                [
                    row["iou"]
                    for row
                    in successful_patient_results
                ],
                dtype=np.float64,
            )

            patient_dscs = np.asarray(
                [
                    row["dsc"]
                    for row
                    in successful_patient_results
                ],
                dtype=np.float64,
            )

            print(
                f"\n  Patient mean IoU: "
                f"{patient_ious.mean():.4f}"
            )

            print(
                f"  Patient mean DSC: "
                f"{patient_dscs.mean():.4f}"
            )

    # ==========================================================
    # IMAGE-LEVEL METRICS CSV
    # ==========================================================

    fieldnames = [
        "patient_id",
        "image_id",
        "view",

        "image_name",
        "image_path",
        "mask_path",

        "prediction_path",
        "overlay_path",

        "height",
        "width",

        "stage1_foreground_pixels",
        "final_foreground_pixels",
        "ground_truth_foreground_pixels",

        "iou",
        "dsc",
        "iou_below_0_3",

        "status",
        "error",
    ]

    with METRICS_CSV.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as csv_file:

        writer = csv.DictWriter(
            csv_file,
            fieldnames=fieldnames,
        )

        writer.writeheader()

        writer.writerows(
            results
        )


    # PATIENT-LEVEL METRICS CSV


    save_patient_metrics(
        results,
        PATIENT_METRICS_CSV,
    )

    # ==========================================================
    # Dataset summary
    # ==========================================================

    successful_results = [
        row
        for row in results
        if row["status"] == "ok"
    ]

    print(
        "\n"
        + "=" * 72
    )

    print(
        "SCREENED PATIENT INFERENCE COMPLETE"
    )

    print(
        "=" * 72
    )

    print(
        f"Patients screened: "
        f"{len(patients)}"
    )

    print(
        f"Images screened: "
        f"{total_screened_images}"
    )

    print(
        f"Successfully processed: "
        f"{len(successful_results)}"
    )

    print(
        f"Failed: "
        f"{failed_count}"
    )

  
    # Overall image-level metrics

    if successful_results:

        ious = np.asarray(
            [
                row["iou"]
                for row
                in successful_results
            ],
            dtype=np.float64,
        )

        dscs = np.asarray(
            [
                row["dsc"]
                for row
                in successful_results
            ],
            dtype=np.float64,
        )

        print(
            f"Mean IoU: "
            f"{ious.mean():.4f}"
        )

        print(
            f"Median IoU: "
            f"{np.median(ious):.4f}"
        )

        print(
            f"Mean DSC: "
            f"{dscs.mean():.4f}"
        )

        print(
            f"Median DSC: "
            f"{np.median(dscs):.4f}"
        )

        print(
            f"IoU below 0.3: "
            f"{int(np.sum(ious < 0.3))}"
        )

    print(
        f"\nImage metrics CSV: "
        f"{METRICS_CSV}"
    )

    print(
        f"Patient metrics CSV: "
        f"{PATIENT_METRICS_CSV}"
    )

    print(
        f"Predicted masks: "
        f"{PREDICTION_DIR}"
    )

    if SAVE_OVERLAYS:

        print(
            f"Individual overlays: "
            f"{OVERLAY_DIR}"
        )

        print(
            f"Patient comparisons: "
            f"{PATIENT_COMPARISON_DIR}"
        )


if __name__ == "__main__":
    main()

Using device: mps
Screened patients: 839
Screened images: 949
Raw images indexed: 9541
Masks indexed: 9541
Loading Stage-1 model...
Loading Stage-2 model...

========================================================================
PATIENT [1/839] 00000127
Screened images: 1
========================================================================

  [1/1] 00000127_1914A778_1
  View: Unknown
  IoU: 0.7176
  DSC: 0.8356

  Patient mean IoU: 0.7176
  Patient mean DSC: 0.8356

========================================================================
PATIENT [2/839] 00000139
Screened images: 2
========================================================================

  [1/2] 00000139_FA7E0544_0
  View: Longitudinal

/var/folders/gd/p6nf_1w11938t89t0bj2r9lc0000gn/T/ipykernel_42433/1610858530.py:153: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  Image.fromarray(mask_uint8, mode="L").save(output_path)
/var/folders/gd/p6nf_1w11938t89t0bj2r9lc0000gn/T/ipykernel_42433/1610858530.py:195: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  Image.fromarray((np.clip(rgb, 0, 1) * 255).astype(np.uint8), mode="RGB").save(

  IoU: 0.4744
  DSC: 0.6435

  [2/2] 00000139_217557BB_1
  View: Unknown
  IoU: 0.8230
  DSC: 0.9029

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000139_comparison.png

  Patient mean IoU: 0.6487
  Patient mean DSC: 0.7732

========================================================================
PATIENT [3/839] 00000141
Screened images: 1
========================================================================

  [1/1] 00000141_CFD4B94F_0
  View: Transverse
  IoU: 0.9106
  DSC: 0.9532

  Patient mean IoU: 0.9106
  Patient mean DSC: 0.9532

========================================================================
PATIENT [4/839] 00000146
Screened images: 1
========================================================================

  [1/1] 00000146_8EC61D31_1
  View: Transverse
  IoU: 0.8351
  DSC: 0.9102

  Patient mean IoU: 0.8351
  Patient mean DSC: 0.9102

========================================================================
PATIENT [5/839] 00000152
Screened images: 1
========================================================================

  [1/1] 00000152_FED1C9E5_2
  View: Transverse
  IoU: 0.7855
  DSC: 0.8799

  Patient mean IoU: 0.7855
  Patient mean DSC: 0.8799

========================================================================
PATIENT [6/839] 00000156
Screened images: 1
========================================================================

  [1/1] 00000156_D1280CBD_2
  View: Longitudinal
  IoU: 0.6420
  DSC: 0.7819

  Patient mean IoU: 0.6420
  Patient mean DSC: 0.7819

========================================================================
PATIENT [7/839] 00000187
Screened images: 2
========================================================================

  [1/2] 00000187_B7BAEC3B_3
  View: Longitudinal
  IoU: 0.8438
  DSC: 0.9153

  [2/2] 00000187_3F6254BA_1
  View: Transverse
  IoU: 0.7432
  DSC: 0.8527

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000187_comparison.png

  Patient mean IoU: 0.7935
  Patient mean DSC: 0.8840

========================================================================
PATIENT [8/839] 00000196
Screened images: 1
========================================================================

  [1/1] 00000196_E68FE536_4
  View: Longitudinal
  IoU: 0.8330
  DSC: 0.9089

  Patient mean IoU: 0.8330
  Patient mean DSC: 0.9089

========================================================================
PATIENT [9/839] 00000198
Screened images: 1
========================================================================

  [1/1] 00000198_68B7897E_1
  View: Transverse
  IoU: 0.6720
  DSC: 0.8038

  Patient mean IoU: 0.6720
  Patient mean DSC: 0.8038

========================================================================
PATIENT [10/839] 00000201
Screened images: 1
========================================================================

  [1/1] 00000201_469369E6_0
  View: Transverse
  IoU: 0.7701
  DSC: 0.8701

  Patient mean IoU: 0.7701
  Patient mean DSC: 0.8701

========================================================================
PATIENT [11/839] 00000204
Screened images: 1
========================================================================

  [1/1] 00000204_C078DA98_0
  View: Longitudinal
  IoU: 0.7024
  DSC: 0.8252

  Patient mean IoU: 0.7024
  Patient mean DSC: 0.8252

========================================================================
PATIENT [12/839] 00000210
Screened images: 1
========================================================================

  [1/1] 00000210_BD5B2A8B_1
  View: Unknown
  IoU: 0.6399
  DSC: 0.7804

  Patient mean IoU: 0.6399
  Patient mean DSC: 0.7804

========================================================================
PATIENT [13/839] 00000212
Screened images: 1
========================================================================

  [1/1] 00000212_1C93ADE2_2
  View: Unknown
  IoU: 0.5866
  DSC: 0.7395

  Patient mean IoU: 0.5866
  Patient mean DSC: 0.7395

========================================================================
PATIENT [14/839] 00000216
Screened images: 1
========================================================================

  [1/1] 00000216_92E33BA4_1
  View: Longitudinal
  IoU: 0.4714
  DSC: 0.6408

  Patient mean IoU: 0.4714
  Patient mean DSC: 0.6408

========================================================================
PATIENT [15/839] 00000218
Screened images: 1
========================================================================

  [1/1] 00000218_3D7A6ECF_1
  View: Transverse
  IoU: 0.6715
  DSC: 0.8035

  Patient mean IoU: 0.6715
  Patient mean DSC: 0.8035

========================================================================
PATIENT [16/839] 00000224
Screened images: 2
========================================================================

  [1/2] 00000224_64C74D7C_2
  View: Unknown
  IoU: 0.5993
  DSC: 0.7495

  [2/2] 00000224_5A545258_1
  View: Transverse
  IoU: 0.7611
  DSC: 0.8644

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000224_comparison.png

  Patient mean IoU: 0.6802
  Patient mean DSC: 0.8069

========================================================================
PATIENT [17/839] 00000235
Screened images: 1
========================================================================

  [1/1] 00000235_ADBEED1D_0
  View: Transverse
  IoU: 0.7201
  DSC: 0.8373

  Patient mean IoU: 0.7201
  Patient mean DSC: 0.8373

========================================================================
PATIENT [18/839] 00000239
Screened images: 1
========================================================================

  [1/1] 00000239_C2174724_1
  View: Transverse
  IoU: 0.7907
  DSC: 0.8831

  Patient mean IoU: 0.7907
  Patient mean DSC: 0.8831

========================================================================
PATIENT [19/839] 00000242
Screened images: 1
========================================================================

  [1/1] 00000242_B2BA5E1E_2
  View: Longitudinal
  IoU: 0.8986
  DSC: 0.9466

  Patient mean IoU: 0.8986
  Patient mean DSC: 0.9466

========================================================================
PATIENT [20/839] 00000244
Screened images: 1
========================================================================

  [1/1] 00000244_B8CF86FD_0
  View: Longitudinal
  IoU: 0.8201
  DSC: 0.9012

  Patient mean IoU: 0.8201
  Patient mean DSC: 0.9012

========================================================================
PATIENT [21/839] 00000248
Screened images: 2
========================================================================

  [1/2] 00000248_6C137413_0
  View: Longitudinal
  IoU: 0.8843
  DSC: 0.9386

  [2/2] 00000248_66728400_2
  View: Transverse
  IoU: 0.8448
  DSC: 0.9159

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000248_comparison.png

  Patient mean IoU: 0.8645
  Patient mean DSC: 0.9272

========================================================================
PATIENT [22/839] 00000251
Screened images: 1
========================================================================

  [1/1] 00000251_D2576CA0_0
  View: Longitudinal
  IoU: 0.6837
  DSC: 0.8122

  Patient mean IoU: 0.6837
  Patient mean DSC: 0.8122

========================================================================
PATIENT [23/839] 00000261
Screened images: 2
========================================================================

  [1/2] 00000261_A5969F13_3
  View: Longitudinal
  IoU: 0.6644
  DSC: 0.7984

  [2/2] 00000261_D6C54E9E_0
  View: Longitudinal
  IoU: 0.8335
  DSC: 0.9092

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000261_comparison.png

  Patient mean IoU: 0.7490
  Patient mean DSC: 0.8538

========================================================================
PATIENT [24/839] 00000272
Screened images: 1
========================================================================

  [1/1] 00000272_AE3A1572_4
  View: Unknown
  IoU: 0.7935
  DSC: 0.8849

  Patient mean IoU: 0.7935
  Patient mean DSC: 0.8849

========================================================================
PATIENT [25/839] 00000276
Screened images: 1
========================================================================

  [1/1] 00000276_6979839F_1
  View: Unknown
  IoU: 0.8577
  DSC: 0.9234

  Patient mean IoU: 0.8577
  Patient mean DSC: 0.9234

========================================================================
PATIENT [26/839] 00000298
Screened images: 1
========================================================================

  [1/1] 00000298_233B954B_2
  View: Longitudinal
  IoU: 0.4015
  DSC: 0.5729

  Patient mean IoU: 0.4015
  Patient mean DSC: 0.5729

========================================================================
PATIENT [27/839] 00000299
Screened images: 1
========================================================================

  [1/1] 00000299_9987EB8C_0
  View: Longitudinal
  IoU: 0.7688
  DSC: 0.8693

  Patient mean IoU: 0.7688
  Patient mean DSC: 0.8693

========================================================================
PATIENT [28/839] 00000308
Screened images: 1
========================================================================

  [1/1] 00000308_D3359A82_1
  View: Unknown
  IoU: 0.6868
  DSC: 0.8144

  Patient mean IoU: 0.6868
  Patient mean DSC: 0.8144

========================================================================
PATIENT [29/839] 00000312
Screened images: 1
========================================================================

  [1/1] 00000312_FEF36D32_1
  View: Longitudinal
  IoU: 0.7308
  DSC: 0.8445

  Patient mean IoU: 0.7308
  Patient mean DSC: 0.8445

========================================================================
PATIENT [30/839] 00000314
Screened images: 1
========================================================================

  [1/1] 00000314_3454A9F7_0
  View: Unknown
  IoU: 0.5919
  DSC: 0.7437

  Patient mean IoU: 0.5919
  Patient mean DSC: 0.7437

========================================================================
PATIENT [31/839] 00000320
Screened images: 1
========================================================================

  [1/1] 00000320_AC171F00_1
  View: Unknown
  IoU: 0.8720
  DSC: 0.9316

  Patient mean IoU: 0.8720
  Patient mean DSC: 0.9316

========================================================================
PATIENT [32/839] 00000325
Screened images: 1
========================================================================

  [1/1] 00000325_AD10BBEF_2
  View: Transverse
  IoU: 0.5605
  DSC: 0.7183

  Patient mean IoU: 0.5605
  Patient mean DSC: 0.7183

========================================================================
PATIENT [33/839] 00000333
Screened images: 2
========================================================================

  [1/2] 00000333_428B7BD7_0
  View: Transverse
  IoU: 0.8421
  DSC: 0.9143

  [2/2] 00000333_6549FB43_2
  View: Longitudinal
  IoU: 0.7670
  DSC: 0.8681

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000333_comparison.png

  Patient mean IoU: 0.8046
  Patient mean DSC: 0.8912

========================================================================
PATIENT [34/839] 00000341
Screened images: 1
========================================================================

  [1/1] 00000341_6DA406B8_2
  View: Longitudinal
  IoU: 0.6250
  DSC: 0.7692

  Patient mean IoU: 0.6250
  Patient mean DSC: 0.7692

========================================================================
PATIENT [35/839] 00000345
Screened images: 1
========================================================================

  [1/1] 00000345_7C72D738_0
  View: Longitudinal
  IoU: 0.5842
  DSC: 0.7375

  Patient mean IoU: 0.5842
  Patient mean DSC: 0.7375

========================================================================
PATIENT [36/839] 00000353
Screened images: 1
========================================================================

  [1/1] 00000353_883F0C38_0
  View: Longitudinal
  IoU: 0.6492
  DSC: 0.7873

  Patient mean IoU: 0.6492
  Patient mean DSC: 0.7873

========================================================================
PATIENT [37/839] 00000359
Screened images: 1
========================================================================

  [1/1] 00000359_34CC9604_0
  View: Transverse
  IoU: 0.4051
  DSC: 0.5766

  Patient mean IoU: 0.4051
  Patient mean DSC: 0.5766

========================================================================
PATIENT [38/839] 00000362
Screened images: 1
========================================================================

  [1/1] 00000362_67FBC805_3
  View: Transverse
  IoU: 0.5394
  DSC: 0.7008

  Patient mean IoU: 0.5394
  Patient mean DSC: 0.7008

========================================================================
PATIENT [39/839] 00000372
Screened images: 2
========================================================================

  [1/2] 00000372_5CF2D6D2_0
  View: Transverse
  IoU: 0.8338
  DSC: 0.9094

  [2/2] 00000372_2698ED21_1
  View: Longitudinal
  IoU: 0.8639
  DSC: 0.9270

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000372_comparison.png

  Patient mean IoU: 0.8488
  Patient mean DSC: 0.9182

========================================================================
PATIENT [40/839] 00000375
Screened images: 1
========================================================================

  [1/1] 00000375_5E48BB9D_2
  View: Transverse
  IoU: 0.8578
  DSC: 0.9235

  Patient mean IoU: 0.8578
  Patient mean DSC: 0.9235

========================================================================
PATIENT [41/839] 00000378
Screened images: 1
========================================================================

  [1/1] 00000378_EBB49946_0
  View: Longitudinal
  IoU: 0.8227
  DSC: 0.9027

  Patient mean IoU: 0.8227
  Patient mean DSC: 0.9027

========================================================================
PATIENT [42/839] 00000419
Screened images: 1
========================================================================

  [1/1] 00000419_5D93A970_0
  View: Longitudinal
  IoU: 0.8186
  DSC: 0.9003

  Patient mean IoU: 0.8186
  Patient mean DSC: 0.9003

========================================================================
PATIENT [43/839] 00000420
Screened images: 1
========================================================================

  [1/1] 00000420_D5AF1D5D_0
  View: Unknown
  IoU: 0.8855
  DSC: 0.9393

  Patient mean IoU: 0.8855
  Patient mean DSC: 0.9393

========================================================================
PATIENT [44/839] 00000431
Screened images: 1
========================================================================

  [1/1] 00000431_18CF3301_2
  View: Unknown
  IoU: 0.8563
  DSC: 0.9226

  Patient mean IoU: 0.8563
  Patient mean DSC: 0.9226

========================================================================
PATIENT [45/839] 00000433
Screened images: 1
========================================================================

  [1/1] 00000433_732E3F2F_2
  View: Transverse
  IoU: 0.8471
  DSC: 0.9172

  Patient mean IoU: 0.8471
  Patient mean DSC: 0.9172

========================================================================
PATIENT [46/839] 00000437
Screened images: 1
========================================================================

  [1/1] 00000437_B531892A_2
  View: Longitudinal
  IoU: 0.7668
  DSC: 0.8680

  Patient mean IoU: 0.7668
  Patient mean DSC: 0.8680

========================================================================
PATIENT [47/839] 00000438
Screened images: 1
========================================================================

  [1/1] 00000438_62C5D9D4_1
  View: Longitudinal
  IoU: 0.5694
  DSC: 0.7256

  Patient mean IoU: 0.5694
  Patient mean DSC: 0.7256

========================================================================
PATIENT [48/839] 00000440
Screened images: 1
========================================================================

  [1/1] 00000440_5DC20C46_2
  View: Unknown
  IoU: 0.8053
  DSC: 0.8922

  Patient mean IoU: 0.8053
  Patient mean DSC: 0.8922

========================================================================
PATIENT [49/839] 00000441
Screened images: 2
========================================================================

  [1/2] 00000441_9A6CB7CC_0
  View: Transverse
  IoU: 0.6876
  DSC: 0.8149

  [2/2] 00000441_5C6613FD_3
  View: Longitudinal
  IoU: 0.6949
  DSC: 0.8200

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000441_comparison.png

  Patient mean IoU: 0.6913
  Patient mean DSC: 0.8175

========================================================================
PATIENT [50/839] 00000445
Screened images: 1
========================================================================

  [1/1] 00000445_63D7996F_0
  View: Transverse
  IoU: 0.3674
  DSC: 0.5374

  Patient mean IoU: 0.3674
  Patient mean DSC: 0.5374

========================================================================
PATIENT [51/839] 00000449
Screened images: 1
========================================================================

  [1/1] 00000449_026323EF_0
  View: Longitudinal
  IoU: 0.8081
  DSC: 0.8939

  Patient mean IoU: 0.8081
  Patient mean DSC: 0.8939

========================================================================
PATIENT [52/839] 00000450
Screened images: 1
========================================================================

  [1/1] 00000450_9520A5DD_3
  View: Longitudinal
  IoU: 0.6881
  DSC: 0.8152

  Patient mean IoU: 0.6881
  Patient mean DSC: 0.8152

========================================================================
PATIENT [53/839] 00000455
Screened images: 2
========================================================================

  [1/2] 00000455_5A911534_1
  View: Unknown
  IoU: 0.8439
  DSC: 0.9154

  [2/2] 00000455_18370D8A_0
  View: Transverse
  IoU: 0.7362
  DSC: 0.8481

  Comparison saved:
  /Users/JanayeCheong/Documents/radiomics_segmentation_models/TNSCUI2020-Seg-Rank1st/inference_outputs_long_vs_trans_v1_07/patient_view_comparisons/00000455_comparison.png

  Patient mean IoU: 0.7901
  Patient mean DSC: 0.8817

========================================================================
PATIENT [54/839] 00000460
Screened images: 1
========================================================================

  [1/1] 00000460_C8B2D1A0_4
  View: Longitudinal
  IoU: 0.5892
  DSC: 0.7415

  Patient mean IoU: 0.5892
  Patient mean DSC: 0.7415

========================================================================
PATIENT [55/839] 00000467
Screened images: 1
========================================================================

  [1/1] 00000467_81302B0D_3
  View: Longitudinal
  IoU: 0.8453
  DSC: 0.9161

  Patient mean IoU: 0.8453
  Patient mean DSC: 0.9161

========================================================================
PATIENT [56/839] 00000470
Screened images: 1
========================================================================

  [1/1] 00000470_573BE30F_2
  View: Transverse
  IoU: 0.5625
  DSC: 0.7200

  Patient mean IoU: 0.5625
  Patient mean DSC: 0.7200


# ANALYSIS OF PATIENT METRICS

In [84]:
patient_metrics = pd.read_csv(PATIENT_METRICS_CSV)

In [85]:
patient_metrics

,patient_id,total_images,transverse_images,longitudinal_images,unknown_images,transverse_mean_iou,longitudinal_mean_iou,iou_long_minus_trans,transverse_mean_dsc,longitudinal_mean_dsc,dsc_long_minus_trans,has_both_views
0,127,1,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
1,139,2,0,1,1,NaN,0.474364,NaN,NaN,0.643483,NaN,0
2,141,1,1,0,0,0.910585,NaN,NaN,0.953200,NaN,NaN,0
3,146,1,1,0,0,0.835139,NaN,NaN,0.910164,NaN,NaN,0
4,152,1,1,0,0,0.785524,NaN,NaN,0.879881,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
834,4739,1,1,0,0,0.912463,NaN,NaN,0.954228,NaN,NaN,0
835,4751,1,1,0,0,0.892597,NaN,NaN,0.943251,NaN,NaN,0
836,4756,1,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,0
837,4762,1,1,0,0,0.795966,NaN,NaN,0.886393,NaN,NaN,0
838,4771,1,0,1,0,NaN,0.852575,NaN,NaN,0.920422,NaN,0

In [88]:
patient_metrics['has_both_views'].value_counts()

has_both_views
0    794
1     45
Name: count, dtype: int64

In [89]:
two_views = patient_metrics[patient_metrics['has_both_views'] == True]

In [91]:
two_views[[
    "patient_id",
    "transverse_mean_iou",
    "longitudinal_mean_iou",
    "iou_long_minus_trans",
    "transverse_mean_dsc",
    "longitudinal_mean_dsc",
    "dsc_long_minus_trans"
]]

,patient_id,transverse_mean_iou,longitudinal_mean_iou,iou_long_minus_trans,transverse_mean_dsc,longitudinal_mean_dsc,dsc_long_minus_trans
6,187,0.743176,0.843781,0.100605,0.852669,0.915272,0.062604
20,248,0.844813,0.884262,0.039448,0.915879,0.938576,0.022697
32,333,0.842122,0.767007,-0.075115,0.914296,0.868143,-0.046153
38,372,0.833796,0.863882,0.030086,0.909366,0.926971,0.017604
48,441,0.687611,0.694949,0.007338,0.814893,0.820024,0.005131
124,863,0.696815,0.759077,0.062262,0.821321,0.863040,0.041719
135,968,0.460851,0.637814,0.176964,0.630935,0.778860,0.147926
150,1071,0.564799,0.661403,0.096605,0.721880,0.796198,0.074318
176,1175,0.722246,0.679650,-0.042596,0.838726,0.809276,-0.029450
186,1223,0.847556,0.765992,-0.081564,0.917489,0.867383,-0.050105
214,1442,0.864849,0.899129,0.034280,0.927527,0.946885,0.019358
234,1561,0.669373,0.634152,-0.035221,0.801945,0.776124,-0.025822
274,1798,0.458276,0.556237,0.097961,0.628517,0.714848,0.086331
287,1855,0.884609,0.916289,0.031681,0.938772,0.956316,0.017544
308,1962,0.898860,0.745531,-0.153330,0.946737,0.854217,-0.092520
326,2125,0.509822,0.530761,0.020938,0.675341,0.693460,0.018119
375,2368,0.728501,0.777239,0.048739,0.842928,0.874659,0.031731
387,2430,0.546554,0.703936,0.157382,0.706802,0.826247,0.119445
417,2615,0.936671,0.724136,-0.212535,0.967300,0.839998,-0.127301
444,2759,0.652315,0.740392,0.088076,0.789577,0.850833,0.061256
446,2763,0.656838,0.667559,0.010721,0.792881,0.800642,0.007761
461,2831,0.805346,0.814110,0.008765,0.892179,0.897531,0.005352
502,3014,0.512424,0.779037,0.266613,0.677620,0.875796,0.198177
510,3033,0.583986,0.743605,0.159619,0.737362,0.852951,0.115589
513,3037,0.767433,0.859670,0.092237,0.868415,0.924540,0.056125
529,3110,0.948786,0.903706,-0.045080,0.973719,0.949417,-0.024301
562,3220,0.855103,0.901882,0.046779,0.921892,0.948410,0.026517
571,3255,0.960690,0.946125,-0.014565,0.979951,0.972317,-0.007634
572,3257,0.772508,0.830838,0.058330,0.871655,0.907604,0.035949
587,3312,0.553597,0.444570,-0.109026,0.712665,0.615505,-0.097159
603,3372,0.877261,0.793899,-0.083362,0.934618,0.885110,-0.049508
657,3648,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
669,3706,0.564754,0.580427,0.015672,0.721844,0.734519,0.012675
672,3712,0.769321,0.776337,0.007016,0.869623,0.874088,0.004465
674,3719,0.616258,0.895075,0.278816,0.762574,0.944633,0.182059
691,3770,0.834690,0.915933,0.081243,0.909897,0.956122,0.046225
695,3782,0.851457,0.813048,-0.038410,0.919770,0.896885,-0.022885
731,3982,0.894051,0.416564,-0.477487,0.944062,0.588133,-0.355930
757,4066,0.795784,0.723067,-0.072717,0.886281,0.839279,-0.047001
780,4296,0.880371,0.788333,-0.092039,0.936380,0.881640,-0.054740
788,4398,0.652508,0.741518,0.089010,0.787573,0.851577,0.064004
796,4572,0.590654,0.199039,-0.391615,0.742655,0.331998,-0.410658
797,4575,0.912170,0.845671,-0.066499,0.954068,0.916342,-0.037726
805,4594,0.794031,0.574132,-0.219899,0.885192,0.729459,-0.155733
809,4621,0.785401,0.803654,0.018252,0.879804,0.891140,0.011336

In [92]:
print("Number of paired patients:", len(two_views))

print("\nIoU")
print("Transverse mean:", two_views["transverse_mean_iou"].mean())
print("Longitudinal mean:", two_views["longitudinal_mean_iou"].mean())
print("Mean difference:",
      two_views["iou_long_minus_trans"].mean())

print("\nDSC")
print("Transverse mean:", two_views["transverse_mean_dsc"].mean())
print("Longitudinal mean:", two_views["longitudinal_mean_dsc"].mean())
print("Mean difference:",
      two_views["dsc_long_minus_trans"].mean())

Number of paired patients: 45

IoU
Transverse mean: 0.7250897034303594
Longitudinal mean: 0.723187074750881
Mean difference: -0.0019026286794786634

DSC
Transverse mean: 0.8250129154514214
Longitudinal mean: 0.8218437990392091
Mean difference: -0.003169116412212182

In [93]:
two_views = two_views.dropna(subset=[
    "transverse_mean_iou",
    "longitudinal_mean_iou",
    "transverse_mean_dsc",
    "longitudinal_mean_dsc"
])

In [95]:
# IoU
iou_long_higher = (two_views["iou_long_minus_trans"] > 0).sum()
iou_trans_higher = (two_views["iou_long_minus_trans"] < 0).sum()
iou_equal = (two_views["iou_long_minus_trans"] == 0).sum()

# DSC
dsc_long_higher = (two_views["dsc_long_minus_trans"] > 0).sum()
dsc_trans_higher = (two_views["dsc_long_minus_trans"] < 0).sum()
dsc_equal = (two_views["dsc_long_minus_trans"] == 0).sum()

print(f"Total paired patients: {len(two_views)}")

print("\nIoU:")
print(f"Longitudinal higher: {iou_long_higher}")
print(f"Transverse higher:   {iou_trans_higher}")
print(f"Equal:               {iou_equal}")

print("\nDSC:")
print(f"Longitudinal higher: {dsc_long_higher}")
print(f"Transverse higher:   {dsc_trans_higher}")
print(f"Equal:               {dsc_equal}")

Total paired patients: 45

IoU:
Longitudinal higher: 27
Transverse higher:   17
Equal:               1

DSC:
Longitudinal higher: 27
Transverse higher:   17
Equal:               1